###############################################################################
# 02_wgcna_network_construction_FINAL_v2.R
#
# TITLE
# Core WGCNA network construction using GENE-COLLAPSED plasma proteomic features
# (ReDLat proteomic project)
#
# PURPOSE
# This script performs the core WGCNA workflow directly on the gene-collapsed
# expression matrix generated by Script 01:
#
#   01_define_wgcna_input_from_DEP_FINAL_v2.R
#
# IMPORTANT
# WGCNA is performed at the GENE-COLLAPSED level, not aptamer-level.
#
# The input matrix has:
#   rows    = samples
#   columns = EntrezGeneSymbol features
#
# INPUTS FROM SCRIPT 01
#   WGCNA_Workflow_april_V2/results/01_define_wgcna_input_from_DEP/
#     - gene_collapsed_expression_matrix.csv
#     - wgcna_sample_metadata.csv
#     - gene_level_annotation.csv
#     - wgcna_input_manifest.csv
#     - wgcna_input_qc_summary.csv
#
# MAIN OUTPUTS
#   WGCNA_Workflow_april_V2/results/02_WGCNA_core_collapsed_genes/
#     - eigengenes/module_eigengenes_per_sample.csv
#     - tables/gene_module_assignment.csv
#     - tables/module_counts.csv
#     - tables/wgcna_core_summary.csv
#     - qc/
#     - soft_threshold/
#     - network/
#     - modules/
#     - workspace/wgcna_core_collapsed_workspace.RData
#
# AUTHOR
# Matías Pizarro + ChatGPT support
###############################################################################

rm(list = ls())

###############################################################################
# 1) PACKAGES
###############################################################################

cran_pkgs <- c(
  "WGCNA",
  "dynamicTreeCut",
  "dplyr",
  "tibble",
  "readr",
  "ggplot2",
  "stringr"
)

cran_missing <- cran_pkgs[
  !sapply(cran_pkgs, requireNamespace, quietly = TRUE)
]

if (length(cran_missing) > 0) {
  install.packages(cran_missing)
}

invisible(lapply(cran_pkgs, library, character.only = TRUE))

options(stringsAsFactors = FALSE)
options(error = traceback)

WGCNA::allowWGCNAThreads()

###############################################################################
# 2) PATHS
###############################################################################

base_dir <- "C:/Users/mnpiz/Desktop/WGCNA_Workflow_april_V2"

input_dir <- file.path(
  base_dir,
  "results",
  "01_define_wgcna_input_from_DEP"
)

outdir <- file.path(
  base_dir,
  "results",
  "02_WGCNA_core_collapsed_genes"
)

dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

subdirs <- c(
  "qc",
  "soft_threshold",
  "network",
  "modules",
  "eigengenes",
  "tables",
  "workspace"
)

invisible(lapply(
  file.path(outdir, subdirs),
  dir.create,
  recursive = TRUE,
  showWarnings = FALSE
))

expr_file <- file.path(
  input_dir,
  "gene_collapsed_expression_matrix.csv"
)

meta_file <- file.path(
  input_dir,
  "wgcna_sample_metadata.csv"
)

annot_file <- file.path(
  input_dir,
  "gene_level_annotation.csv"
)

manifest_file <- file.path(
  input_dir,
  "wgcna_input_manifest.csv"
)

input_qc_file <- file.path(
  input_dir,
  "wgcna_input_qc_summary.csv"
)

required_files <- c(
  expr_file,
  meta_file,
  annot_file
)

missing_files <- required_files[!file.exists(required_files)]

if (length(missing_files) > 0) {
  stop(
    "Faltan archivos de entrada desde Script 01:\n",
    paste(missing_files, collapse = "\n"),
    "\n\nPrimero corre 01_define_wgcna_input_from_DEP_FINAL_v2.R",
    call. = FALSE
  )
}

###############################################################################
# 3) GLOBAL PARAMETERS
###############################################################################

DEFAULT_SOFT_POWER <- 4
MIN_MODULE_SIZE    <- 30
MERGE_CUT_HEIGHT   <- 0.25
DEEPSPLIT          <- 3
NETWORK_TYPE       <- "signed"

# Si no quieres eliminar outliers por corte manual, deja NA.
OUTLIER_CUT_HEIGHT <- NA_real_

# Si pickSoftThreshold no sugiere uno, se usa DEFAULT_SOFT_POWER.
AUTO_SELECT_SOFT_POWER <- FALSE
TARGET_SCALE_FREE_R2 <- 0.90

###############################################################################
# 4) HELPERS
###############################################################################

safe_write_csv <- function(x, file) {
  dir.create(dirname(file), recursive = TRUE, showWarnings = FALSE)
  readr::write_csv(x, file)
}

clean_text_na <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x[x %in% c("", "NA", "NaN", "NULL", "null", "N/A", "nan")] <- NA_character_
  x
}

safe_numeric <- function(x) {
  suppressWarnings(as.numeric(x))
}

make_display_name <- function(x) {
  x <- as.character(x)
  x[is.na(x) | x == ""] <- "Unknown_protein"
  make.unique(x, sep = "_dup")
}

select_soft_power <- function(sft_fit_indices,
                              default_power = 4,
                              target_r2 = 0.90,
                              auto_select = FALSE) {
  if (!auto_select) {
    return(default_power)
  }

  fit_df <- as.data.frame(sft_fit_indices)

  if (!all(c("Power", "SFT.R.sq", "slope") %in% names(fit_df))) {
    return(default_power)
  }

  fit_df <- fit_df %>%
    dplyr::mutate(
      signed_R2 = -sign(slope) * SFT.R.sq
    )

  candidate <- fit_df %>%
    dplyr::filter(signed_R2 >= target_r2) %>%
    dplyr::arrange(Power) %>%
    dplyr::slice(1)

  if (nrow(candidate) == 1) {
    return(candidate$Power[[1]])
  }

  default_power
}

###############################################################################
# 5) LOAD INPUTS FROM SCRIPT 01
###############################################################################

expr_gene_df <- readr::read_csv(expr_file, show_col_types = FALSE)
meta_df <- readr::read_csv(meta_file, show_col_types = FALSE)
gene_annotation <- readr::read_csv(annot_file, show_col_types = FALSE)

if (file.exists(manifest_file)) {
  manifest_df <- readr::read_csv(manifest_file, show_col_types = FALSE)
} else {
  manifest_df <- NULL
}

if (file.exists(input_qc_file)) {
  input_qc_df <- readr::read_csv(input_qc_file, show_col_types = FALSE)
} else {
  input_qc_df <- NULL
}

cat("INPUT DIMENSIONS\n")
cat("expr_gene_df    :", dim(expr_gene_df), "\n")
cat("meta_df         :", dim(meta_df), "\n")
cat("gene_annotation :", dim(gene_annotation), "\n\n")

cat("Input directory:\n")
cat(input_dir, "\n\n")

###############################################################################
# 6) BASIC INPUT CHECKS
###############################################################################

if (!"SampleId" %in% names(expr_gene_df)) {
  stop("expr_gene_df debe contener la columna SampleId.", call. = FALSE)
}

if (!"SampleId" %in% names(meta_df)) {
  stop("meta_df debe contener la columna SampleId.", call. = FALSE)
}

if (!"EntrezGeneSymbol" %in% names(gene_annotation)) {
  stop("gene_annotation debe contener la columna EntrezGeneSymbol.", call. = FALSE)
}

expr_gene_df <- expr_gene_df %>%
  dplyr::mutate(SampleId = as.character(SampleId)) %>%
  dplyr::distinct(SampleId, .keep_all = TRUE)

meta_df <- meta_df %>%
  dplyr::mutate(SampleId = as.character(SampleId)) %>%
  dplyr::distinct(SampleId, .keep_all = TRUE)

gene_annotation <- gene_annotation %>%
  dplyr::mutate(
    EntrezGeneSymbol = clean_text_na(EntrezGeneSymbol),
    Protein_Name = if ("Protein_Name" %in% names(.)) clean_text_na(Protein_Name) else NA_character_,
    AptName = if ("AptName" %in% names(.)) clean_text_na(AptName) else NA_character_
  ) %>%
  dplyr::filter(
    !is.na(EntrezGeneSymbol),
    EntrezGeneSymbol != ""
  ) %>%
  dplyr::distinct(EntrezGeneSymbol, .keep_all = TRUE)

###############################################################################
# 7) PREPARE datExpr
###############################################################################

meta_df <- meta_df %>%
  dplyr::filter(SampleId %in% expr_gene_df$SampleId)

expr_gene_df <- expr_gene_df %>%
  dplyr::filter(SampleId %in% meta_df$SampleId)

meta_df <- meta_df %>%
  dplyr::arrange(SampleId)

expr_gene_df <- expr_gene_df %>%
  dplyr::arrange(SampleId)

stopifnot(all(meta_df$SampleId == expr_gene_df$SampleId))

rownames_expr <- expr_gene_df$SampleId

expr_only <- expr_gene_df %>%
  dplyr::select(-SampleId)

expr_only <- as.data.frame(expr_only)
expr_only[] <- lapply(expr_only, safe_numeric)

datExpr0 <- as.data.frame(as.matrix(expr_only))
rownames(datExpr0) <- rownames_expr

# Asegurar que solo queden genes anotados.
common_genes <- intersect(
  colnames(datExpr0),
  gene_annotation$EntrezGeneSymbol
)

if (length(common_genes) == 0) {
  stop(
    "No hay intersección entre columnas de expresión y EntrezGeneSymbol en gene_annotation.",
    call. = FALSE
  )
}

datExpr0 <- datExpr0[, common_genes, drop = FALSE]

gene_annotation <- gene_annotation %>%
  dplyr::filter(EntrezGeneSymbol %in% common_genes)

cat("Initial datExpr0 dimensions (samples x genes):\n")
cat(dim(datExpr0), "\n\n")

safe_write_csv(
  gene_annotation,
  file.path(outdir, "tables", "gene_level_annotation_used.csv")
)

###############################################################################
# 8) QC — goodSamplesGenes
###############################################################################

gsg <- WGCNA::goodSamplesGenes(datExpr0, verbose = 3)

datExpr <- datExpr0[
  gsg$goodSamples,
  gsg$goodGenes,
  drop = FALSE
]

meta_clean <- meta_df[
  gsg$goodSamples,
  ,
  drop = FALSE
]

qc_tbl <- tibble::tibble(
  metric = c(
    "samples_input",
    "genes_input",
    "samples_after_goodSamplesGenes",
    "genes_after_goodSamplesGenes",
    "wgcna_input_level"
  ),
  value = c(
    as.character(nrow(datExpr0)),
    as.character(ncol(datExpr0)),
    as.character(nrow(datExpr)),
    as.character(ncol(datExpr)),
    "GENE-COLLAPSED, not aptamer-level"
  )
)

safe_write_csv(
  qc_tbl,
  file.path(outdir, "qc", "qc_summary.csv")
)

cat("QC summary:\n")
print(qc_tbl)
cat("\n")

###############################################################################
# 9) SAMPLE CLUSTERING AND OPTIONAL OUTLIER REMOVAL
###############################################################################

sampleTree <- hclust(
  dist(datExpr),
  method = "average"
)

pdf(
  file.path(outdir, "qc", "sample_clustering.pdf"),
  width = 10,
  height = 6
)

plot(
  sampleTree,
  main = "Sample clustering (gene-collapsed matrix)",
  xlab = "",
  sub = ""
)

if (!is.na(OUTLIER_CUT_HEIGHT)) {
  abline(h = OUTLIER_CUT_HEIGHT, col = "red")
}

dev.off()

datExpr_clean <- datExpr
meta_final <- meta_clean

if (!is.na(OUTLIER_CUT_HEIGHT)) {
  clust <- WGCNA::cutreeStatic(
    sampleTree,
    cutHeight = OUTLIER_CUT_HEIGHT,
    minSize = 10
  )

  keep_idx <- which(clust == 1)

  if (length(keep_idx) >= 10) {
    datExpr_clean <- datExpr[keep_idx, , drop = FALSE]
    meta_final <- meta_clean[keep_idx, , drop = FALSE]
  }
}

outlier_tbl <- tibble::tibble(
  samples_before_outlier_removal = nrow(datExpr),
  samples_after_outlier_removal = nrow(datExpr_clean),
  outlier_cut_height = OUTLIER_CUT_HEIGHT
)

safe_write_csv(
  outlier_tbl,
  file.path(outdir, "qc", "outlier_summary.csv")
)

cat("Outlier summary:\n")
print(outlier_tbl)
cat("\n")

###############################################################################
# 10) SOFT-THRESHOLD SELECTION
###############################################################################

powers <- c(1:10, seq(12, 30, by = 2))

sft <- WGCNA::pickSoftThreshold(
  datExpr_clean,
  powerVector = powers,
  verbose = 5,
  networkType = NETWORK_TYPE
)

pdf(
  file.path(outdir, "soft_threshold", "soft_threshold_diagnostics.pdf"),
  width = 12,
  height = 6
)

par(mfrow = c(1, 2))

plot(
  sft$fitIndices[, 1],
  -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
  xlab = "Soft Threshold (power)",
  ylab = "Scale Free Topology Model Fit, signed R²",
  type = "n",
  main = "Scale independence"
)

text(
  sft$fitIndices[, 1],
  -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
  labels = sft$fitIndices[, 1],
  cex = 0.8,
  col = "darkred"
)

abline(h = TARGET_SCALE_FREE_R2, col = "blue", lty = 2)

plot(
  sft$fitIndices[, 1],
  sft$fitIndices[, 5],
  xlab = "Soft Threshold (power)",
  ylab = "Mean Connectivity",
  type = "n",
  main = "Mean connectivity"
)

text(
  sft$fitIndices[, 1],
  sft$fitIndices[, 5],
  labels = sft$fitIndices[, 1],
  cex = 0.8,
  col = "darkred"
)

dev.off()

softPower <- select_soft_power(
  sft_fit_indices = sft$fitIndices,
  default_power = DEFAULT_SOFT_POWER,
  target_r2 = TARGET_SCALE_FREE_R2,
  auto_select = AUTO_SELECT_SOFT_POWER
)

soft_tbl <- tibble::tibble(
  chosen_soft_power = softPower,
  default_soft_power_if_needed = DEFAULT_SOFT_POWER,
  auto_select_soft_power = AUTO_SELECT_SOFT_POWER,
  target_scale_free_R2 = TARGET_SCALE_FREE_R2,
  network_type = NETWORK_TYPE
)

safe_write_csv(
  as.data.frame(sft$fitIndices),
  file.path(outdir, "soft_threshold", "soft_threshold_scan.csv")
)

safe_write_csv(
  soft_tbl,
  file.path(outdir, "soft_threshold", "soft_threshold_selected.csv")
)

cat("Selected soft power: ", softPower, "\n\n")

###############################################################################
# 11) NETWORK CONSTRUCTION
###############################################################################

adjacency_mat <- WGCNA::adjacency(
  datExpr_clean,
  power = softPower,
  type = NETWORK_TYPE
)

TOM <- WGCNA::TOMsimilarity(
  adjacency_mat,
  TOMType = NETWORK_TYPE
)

dissTOM <- 1 - TOM

geneTree <- hclust(
  as.dist(dissTOM),
  method = "average"
)

pdf(
  file.path(outdir, "network", "gene_clustering_dendrogram.pdf"),
  width = 12,
  height = 6
)

plot(
  geneTree,
  xlab = "",
  sub = "",
  main = "Gene clustering on TOM-based dissimilarity",
  labels = FALSE,
  hang = 0.04
)

dev.off()

###############################################################################
# 12) INITIAL MODULE DETECTION
###############################################################################

dynamicMods <- dynamicTreeCut::cutreeDynamic(
  dendro = geneTree,
  distM = dissTOM,
  deepSplit = DEEPSPLIT,
  pamRespectsDendro = FALSE,
  minClusterSize = MIN_MODULE_SIZE
)

dynamicColors <- WGCNA::labels2colors(dynamicMods)

pdf(
  file.path(outdir, "modules", "dynamic_modules_dendrogram.pdf"),
  width = 12,
  height = 6
)

WGCNA::plotDendroAndColors(
  geneTree,
  dynamicColors,
  "Dynamic Tree Cut",
  dendroLabels = FALSE,
  hang = 0.03,
  addGuide = TRUE,
  guideHang = 0.05,
  main = "Gene dendrogram and initial module colors"
)

dev.off()

###############################################################################
# 13) MODULE EIGENGENES AND MERGING
###############################################################################

MEList <- WGCNA::moduleEigengenes(
  datExpr_clean,
  colors = dynamicColors
)

MEs <- WGCNA::orderMEs(MEList$eigengenes)

MEDiss <- 1 - cor(MEs, use = "pairwise.complete.obs")

METree <- hclust(
  as.dist(MEDiss),
  method = "average"
)

pdf(
  file.path(outdir, "modules", "module_eigengene_clustering.pdf"),
  width = 7,
  height = 6
)

plot(
  METree,
  main = "Clustering of module eigengenes"
)

abline(
  h = MERGE_CUT_HEIGHT,
  col = "red"
)

dev.off()

merge <- WGCNA::mergeCloseModules(
  datExpr_clean,
  dynamicColors,
  cutHeight = MERGE_CUT_HEIGHT,
  verbose = 3
)

mergedColors <- merge$colors
mergedMEs <- WGCNA::orderMEs(merge$newMEs)

pdf(
  file.path(outdir, "modules", "merged_modules_dendrogram.pdf"),
  width = 12,
  height = 6
)

WGCNA::plotDendroAndColors(
  geneTree,
  cbind(dynamicColors, mergedColors),
  c("Initial modules", "Merged modules"),
  dendroLabels = FALSE,
  hang = 0.03,
  addGuide = TRUE,
  guideHang = 0.05,
  main = "Gene dendrogram and merged module colors"
)

dev.off()

###############################################################################
# 14) MODULE COUNTS
###############################################################################

module_counts <- sort(
  table(mergedColors),
  decreasing = TRUE
)

module_count_tbl <- tibble::tibble(
  Module = names(module_counts),
  N_genes = as.integer(module_counts),
  Prop_total = as.integer(module_counts) / sum(module_counts)
)

safe_write_csv(
  module_count_tbl,
  file.path(outdir, "tables", "module_counts.csv")
)

pdf(
  file.path(outdir, "modules", "module_barplot.pdf"),
  width = 9,
  height = 6
)

par(mar = c(8, 5, 3, 1))

barplot(
  module_counts,
  las = 2,
  col = names(module_counts),
  main = "Number of genes per module",
  ylab = "Number of genes",
  border = NA
)

dev.off()

cat("Module count table:\n")
print(module_count_tbl)
cat("\n")

###############################################################################
# 15) GENE → MODULE ASSIGNMENT TABLE
###############################################################################

if (!"Protein_Name" %in% names(gene_annotation)) {
  gene_annotation$Protein_Name <- gene_annotation$EntrezGeneSymbol
}

if (!"Protein_Display" %in% names(gene_annotation)) {
  gene_annotation$Protein_Display <- gene_annotation$Protein_Name
}

gene_module_assignment <- tibble::tibble(
  EntrezGeneSymbol = colnames(datExpr_clean),
  Module = mergedColors
) %>%
  dplyr::left_join(
    gene_annotation,
    by = "EntrezGeneSymbol"
  ) %>%
  dplyr::mutate(
    Protein_Name = dplyr::coalesce(Protein_Name, EntrezGeneSymbol),
    Protein_Display = dplyr::coalesce(Protein_Display, Protein_Name)
  ) %>%
  dplyr::left_join(
    module_count_tbl,
    by = "Module"
  ) %>%
  dplyr::arrange(Module, Protein_Name)

safe_write_csv(
  gene_module_assignment,
  file.path(outdir, "tables", "gene_module_assignment.csv")
)

###############################################################################
# 16) MODULE EIGENGENES PER SAMPLE
###############################################################################

ME_df <- cbind(
  meta_final["SampleId"],
  as.data.frame(mergedMEs)
)

safe_write_csv(
  ME_df,
  file.path(outdir, "eigengenes", "module_eigengenes_per_sample.csv")
)

cat("Eigengene table dimensions:\n")
print(dim(ME_df))
cat("\n")

###############################################################################
# 17) FINAL SUMMARY TABLE
###############################################################################

summary_tbl <- tibble::tibble(
  metric = c(
    "base_dir",
    "input_dir",
    "output_dir",
    "wgcna_input_level",
    "n_samples_input_script2",
    "n_genes_input_script2",
    "n_samples_final_wgcna",
    "n_genes_final_wgcna",
    "soft_power",
    "auto_select_soft_power",
    "target_scale_free_R2",
    "network_type",
    "min_module_size",
    "deepSplit",
    "merge_cut_height",
    "n_modules_final_including_grey"
  ),
  value = c(
    base_dir,
    input_dir,
    outdir,
    "GENE-COLLAPSED, not aptamer-level",
    as.character(nrow(datExpr0)),
    as.character(ncol(datExpr0)),
    as.character(nrow(datExpr_clean)),
    as.character(ncol(datExpr_clean)),
    as.character(softPower),
    as.character(AUTO_SELECT_SOFT_POWER),
    as.character(TARGET_SCALE_FREE_R2),
    NETWORK_TYPE,
    as.character(MIN_MODULE_SIZE),
    as.character(DEEPSPLIT),
    as.character(MERGE_CUT_HEIGHT),
    as.character(length(unique(mergedColors)))
  )
)

safe_write_csv(
  summary_tbl,
  file.path(outdir, "tables", "wgcna_core_summary.csv")
)

cat("Final summary:\n")
print(summary_tbl)
cat("\n")

###############################################################################
# 18) SAVE WORKSPACE
###############################################################################

save(
  expr_gene_df,
  meta_df,
  meta_clean,
  meta_final,
  gene_annotation,
  manifest_df,
  input_qc_df,
  datExpr0,
  datExpr,
  datExpr_clean,
  sampleTree,
  sft,
  softPower,
  adjacency_mat,
  TOM,
  dissTOM,
  geneTree,
  dynamicMods,
  dynamicColors,
  mergedColors,
  mergedMEs,
  module_count_tbl,
  gene_module_assignment,
  ME_df,
  summary_tbl,
  file = file.path(outdir, "workspace", "wgcna_core_collapsed_workspace.RData")
)

writeLines(
  capture.output(utils::sessionInfo()),
  con = file.path(outdir, "sessionInfo.txt")
)

###############################################################################
# 19) FINAL MESSAGE
###############################################################################

cat("\nWGCNA core workflow on GENE-COLLAPSED features finished successfully.\n")
cat("Main output directory:\n", outdir, "\n")
cat("Input level: GENE-COLLAPSED, not aptamer-level.\n")
cat("Main output for Script 03:\n")
cat(file.path(outdir, "workspace", "wgcna_core_collapsed_workspace.RData"), "\n")
cat(file.path(outdir, "tables", "gene_module_assignment.csv"), "\n")

###############################################################################
# END
###############################################################################

