##############################################################################
# 03_WGCNA_module_biology_hubs_enrichment_FINAL_v4.R
#
# TITLE
# Biological interpretation of GENE-COLLAPSED WGCNA modules
# (hubs + functional enrichment + optional network export)
#
# PURPOSE
# This script takes the final WGCNA objects generated by Script 02 and performs:
#   1) kME / module membership calculation
#   2) hub prioritization within WGCNA modules
#   3) robust functional enrichment by module: GO BP, KEGG, Reactome
#   4) export of node tables for optional STRING/Cytoscape analysis
#
# IMPORTANT
# This script uses modules generated from GENE-COLLAPSED features.
# It does NOT use aptamer-level WGCNA modules.
#
# KEY UPDATE IN v3/v4
# Enrichment is no longer allowed to fail silently or return only zeros without
# diagnostic files. The script now:
#   - maps SYMBOL -> ENTREZID robustly
#   - runs enrichment with permissive cutoffs to retrieve candidate terms
#   - exports all terms, significant terms, and top terms separately
#   - counts FDR-significant terms for module prioritization
#   - writes error messages per module/library if enrichment fails
#   - uses real module colors in hub figures and node tables
#   - v4 fixes vectorized module color assignment
#
# INPUTS FROM SCRIPT 02
#   WGCNA_Workflow_april_V2/results/02_WGCNA_core_collapsed_genes/
#     - workspace/wgcna_core_collapsed_workspace.RData
#     - tables/gene_module_assignment.csv
#
# MAIN OUTPUTS
#   WGCNA_Workflow_april_V2/results/03_WGCNA_module_biology_hubs_enrichment/
#     - tables/full_kME_table_wide.csv
#     - tables/full_kME_assigned_module_long.csv
#     - tables/module_hub_summary.csv
#     - tables/enrichment_summary_by_module.csv
#     - hubs/top_hubs_<module>.csv
#     - enrichment/GO_BP/*.csv
#     - enrichment/KEGG/*.csv
#     - enrichment/Reactome/*.csv
#     - figures/hubs/*.pdf/png
#     - figures/enrichment/*.pdf/png
#     - network_optional/nodes_top_hubs_<module>.csv
#
# AUTHOR
# Matías Pizarro + ChatGPT support
##############################################################################

rm(list = ls())

###############################################################################
# 1) PACKAGES
###############################################################################

cran_pkgs <- c(
  "dplyr",
  "tibble",
  "readr",
  "stringr",
  "ggplot2",
  "purrr",
  "tidyr",
  "forcats"
)

bioc_pkgs <- c(
  "WGCNA",
  "clusterProfiler",
  "ReactomePA",
  "org.Hs.eg.db",
  "enrichplot"
)

cran_missing <- cran_pkgs[
  !sapply(cran_pkgs, requireNamespace, quietly = TRUE)
]

if (length(cran_missing) > 0) {
  install.packages(cran_missing)
}

if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}

bioc_missing <- bioc_pkgs[
  !sapply(bioc_pkgs, requireNamespace, quietly = TRUE)
]

if (length(bioc_missing) > 0) {
  BiocManager::install(bioc_missing, ask = FALSE, update = FALSE)
}

invisible(lapply(c(cran_pkgs, bioc_pkgs), library, character.only = TRUE))

options(stringsAsFactors = FALSE)
options(error = traceback)

###############################################################################
# 2) PATHS
###############################################################################

base_dir <- "C:/Users/mnpiz/Desktop/WGCNA_Workflow_april_V2"

core_dir <- file.path(
  base_dir,
  "results",
  "02_WGCNA_core_collapsed_genes"
)

workspace_file <- file.path(
  core_dir,
  "workspace",
  "wgcna_core_collapsed_workspace.RData"
)

gene_module_file <- file.path(
  core_dir,
  "tables",
  "gene_module_assignment.csv"
)

outdir <- file.path(
  base_dir,
  "results",
  "03_WGCNA_module_biology_hubs_enrichment"
)

dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

subdirs <- c(
  "tables",
  "hubs",
  "enrichment",
  "enrichment/GO_BP",
  "enrichment/KEGG",
  "enrichment/Reactome",
  "enrichment/significant",
  "enrichment/top_terms",
  "figures",
  "figures/hubs",
  "figures/enrichment",
  "network_optional",
  "workspace"
)

invisible(lapply(
  file.path(outdir, subdirs),
  dir.create,
  recursive = TRUE,
  showWarnings = FALSE
))

if (!file.exists(workspace_file)) {
  stop(
    "No existe el workspace esperado desde Script 02:\n",
    workspace_file,
    "\n\nPrimero corre 02_wgcna_network_construction_FINAL_v2.R",
    call. = FALSE
  )
}

if (!file.exists(gene_module_file)) {
  stop(
    "No existe gene_module_assignment.csv desde Script 02:\n",
    gene_module_file,
    "\n\nPrimero corre 02_wgcna_network_construction_FINAL_v2.R",
    call. = FALSE
  )
}

###############################################################################
# 3) PARAMETERS
###############################################################################

# NULL = usar automáticamente todos los módulos detectados en mergedMEs excepto grey.
modules_of_interest <- NULL
exclude_modules <- c("grey")

top_hubs_per_module <- 30
top_plot_hubs <- 15

# Enrichment strategy:
# We retrieve candidate terms permissively, then count/report by adjusted p-value.
enrich_retrieve_p_cutoff <- 1
enrich_retrieve_q_cutoff <- 1

enrich_sig_fdr_cutoff <- 0.05
enrich_suggestive_fdr_cutoff <- 0.10

min_genes_for_enrichment <- 10
show_terms_per_plot <- 12

###############################################################################
# 4) COLORS AND HELPERS
###############################################################################

MODULE_COLORS <- c(
  black       = "#2B2B2B",
  brown       = "#9C6B00",
  yellow      = "#B7D500",
  blue        = "#1535E8",
  green       = "#3E8F4E",
  red         = "#B4334A",
  purple      = "#8A2BE2",
  magenta     = "#C75ACD",
  pink        = "#F3A6D6",
  greenyellow = "#ADFF2F",
  grey        = "#9E9E9E"
)

get_module_color <- function(module_name) {
  module_name <- as.character(module_name)

  cols <- MODULE_COLORS[module_name]

  cols[is.na(cols)] <- "#7F7F7F"

  unname(cols)
}

safe_write_csv <- function(x, file) {
  dir.create(dirname(file), recursive = TRUE, showWarnings = FALSE)
  readr::write_csv(x, file)
}

safe_file_tag <- function(x) {
  x <- as.character(x)
  x <- gsub("[^A-Za-z0-9_\\-]+", "_", x)
  x <- gsub("_+", "_", x)
  x <- gsub("^_|_$", "", x)
  x
}

clean_text_na <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x[x %in% c("", "NA", "NaN", "NULL", "null", "N/A", "nan")] <- NA_character_
  x
}

safe_numeric <- function(x) {
  suppressWarnings(as.numeric(x))
}

ensure_column <- function(df, col, default = NA_character_) {
  if (!col %in% names(df)) {
    df[[col]] <- default
  }
  df
}

plot_hub_bar <- function(df_hubs, module_name, n_plot = 15, outdir_fig) {
  if (is.null(df_hubs) || nrow(df_hubs) == 0) return(NULL)

  module_col <- get_module_color(module_name)

  df_plot <- df_hubs %>%
    dplyr::slice(seq_len(min(n_plot, nrow(df_hubs)))) %>%
    dplyr::mutate(
      Protein_Label = dplyr::coalesce(
        Protein_Display,
        Protein_Name,
        EntrezGeneSymbol
      ),
      Protein_Label = factor(Protein_Label, levels = rev(Protein_Label))
    )

  p <- ggplot(df_plot, aes(x = Protein_Label, y = abs_kME)) +
    geom_col(fill = module_col, width = 0.8) +
    coord_flip() +
    labs(
      title = paste0("Top hubs — module ", module_name),
      x = NULL,
      y = "|kME|"
    ) +
    theme_bw(base_size = 12) +
    theme(
      plot.title = element_text(face = "bold"),
      panel.grid.major.y = element_blank(),
      panel.grid.minor = element_blank()
    )

  ggsave(
    filename = file.path(outdir_fig, paste0("top_hubs_barplot_", module_name, ".pdf")),
    plot = p,
    width = 7,
    height = 5
  )

  ggsave(
    filename = file.path(outdir_fig, paste0("top_hubs_barplot_", module_name, ".png")),
    plot = p,
    width = 7,
    height = 5,
    dpi = 300
  )

  return(p)
}

plot_enrichment_bar <- function(res, module_name, analysis_name, outdir_fig, n_show = 12) {
  if (is.null(res) || nrow(res) == 0) return(NULL)

  module_col <- get_module_color(module_name)

  top_res <- res %>%
    dplyr::arrange(p.adjust, pvalue) %>%
    dplyr::slice(seq_len(min(n_show, nrow(res)))) %>%
    dplyr::mutate(
      Description = stringr::str_wrap(Description, width = 45),
      Description = factor(Description, levels = rev(Description)),
      minus_log10_padj = -log10(pmax(p.adjust, .Machine$double.xmin))
    )

  p <- ggplot(top_res, aes(x = Description, y = minus_log10_padj)) +
    geom_col(fill = module_col, width = 0.8) +
    coord_flip() +
    labs(
      title = paste0(analysis_name, " enrichment — ", module_name),
      x = NULL,
      y = expression(-log[10]("FDR"))
    ) +
    theme_bw(base_size = 12) +
    theme(
      plot.title = element_text(face = "bold"),
      panel.grid.major.y = element_blank(),
      panel.grid.minor = element_blank()
    )

  ggsave(
    filename = file.path(outdir_fig, paste0("barplot_", analysis_name, "_", module_name, ".pdf")),
    plot = p,
    width = 8,
    height = 5.5
  )

  ggsave(
    filename = file.path(outdir_fig, paste0("barplot_", analysis_name, "_", module_name, ".png")),
    plot = p,
    width = 8,
    height = 5.5,
    dpi = 300
  )

  return(p)
}

save_enrichment_tables <- function(res, module_name, analysis_name) {
  if (is.null(res)) {
    return(NULL)
  }

  res <- as.data.frame(res)

  if (nrow(res) == 0) {
    return(NULL)
  }

  res <- res %>%
    dplyr::arrange(p.adjust, pvalue)

  safe_write_csv(
    res,
    file.path(outdir, "enrichment", analysis_name, paste0("enrichment_", analysis_name, "_", module_name, "_all_terms.csv"))
  )

  sig <- res %>%
    dplyr::filter(!is.na(p.adjust), p.adjust < enrich_sig_fdr_cutoff)

  safe_write_csv(
    sig,
    file.path(outdir, "enrichment", "significant", paste0("enrichment_", analysis_name, "_", module_name, "_FDR005.csv"))
  )

  top <- res %>%
    dplyr::slice(seq_len(min(show_terms_per_plot, nrow(res))))

  safe_write_csv(
    top,
    file.path(outdir, "enrichment", "top_terms", paste0("enrichment_", analysis_name, "_", module_name, "_top_terms.csv"))
  )

  plot_enrichment_bar(
    res = top,
    module_name = module_name,
    analysis_name = analysis_name,
    outdir_fig = file.path(outdir, "figures", "enrichment"),
    n_show = show_terms_per_plot
  )

  res
}

make_enrich_count <- function(res) {
  if (is.null(res) || nrow(res) == 0) {
    return(tibble::tibble(
      n_terms_total = 0,
      n_terms_fdr_0_05 = 0,
      n_terms_fdr_0_10 = 0,
      min_FDR = NA_real_,
      top_term = NA_character_
    ))
  }

  res <- as.data.frame(res) %>% dplyr::arrange(p.adjust, pvalue)

  tibble::tibble(
    n_terms_total = nrow(res),
    n_terms_fdr_0_05 = sum(!is.na(res$p.adjust) & res$p.adjust < enrich_sig_fdr_cutoff),
    n_terms_fdr_0_10 = sum(!is.na(res$p.adjust) & res$p.adjust < enrich_suggestive_fdr_cutoff),
    min_FDR = suppressWarnings(min(res$p.adjust, na.rm = TRUE)),
    top_term = ifelse(nrow(res) > 0, as.character(res$Description[[1]]), NA_character_)
  ) %>%
    dplyr::mutate(
      min_FDR = ifelse(is.infinite(min_FDR), NA_real_, min_FDR)
    )
}

###############################################################################
# 5) LOAD WORKSPACE AND TABLES
###############################################################################

load(workspace_file)

gene_module_assignment_tbl <- readr::read_csv(
  gene_module_file,
  show_col_types = FALSE
)

cat("Workspace cargado correctamente desde Script 02.\n")
cat("Objetos disponibles:\n")
cat(" - datExpr_clean:", exists("datExpr_clean"), "\n")
cat(" - mergedMEs:", exists("mergedMEs"), "\n")
cat(" - mergedColors:", exists("mergedColors"), "\n")
cat(" - gene_module_assignment:", exists("gene_module_assignment"), "\n\n")

if (!exists("datExpr_clean")) {
  stop("No existe datExpr_clean en el workspace de Script 02.", call. = FALSE)
}

if (!exists("mergedMEs")) {
  stop("No existe mergedMEs en el workspace de Script 02.", call. = FALSE)
}

if (!exists("mergedColors")) {
  stop("No existe mergedColors en el workspace de Script 02.", call. = FALSE)
}

required_module_cols <- c("EntrezGeneSymbol", "Module")
missing_module_cols <- setdiff(required_module_cols, names(gene_module_assignment_tbl))

if (length(missing_module_cols) > 0) {
  stop(
    "gene_module_assignment.csv no contiene columnas requeridas: ",
    paste(missing_module_cols, collapse = ", "),
    call. = FALSE
  )
}

###############################################################################
# 6) BASIC CHECKS AND ANNOTATION HARMONIZATION
###############################################################################

datExpr_clean <- as.data.frame(datExpr_clean)
mergedMEs <- as.data.frame(mergedMEs)

if (nrow(datExpr_clean) != nrow(mergedMEs)) {
  stop("datExpr_clean y mergedMEs no tienen el mismo número de muestras.", call. = FALSE)
}

if (!all(rownames(datExpr_clean) == rownames(mergedMEs))) {
  cat("ADVERTENCIA: el orden de muestras no coincide exactamente. Reordenando mergedMEs...\n")
  mergedMEs <- mergedMEs[rownames(datExpr_clean), , drop = FALSE]
}

gene_module_assignment_tbl <- gene_module_assignment_tbl %>%
  dplyr::mutate(
    EntrezGeneSymbol = clean_text_na(EntrezGeneSymbol),
    Module = clean_text_na(Module)
  ) %>%
  dplyr::filter(!is.na(EntrezGeneSymbol), !is.na(Module)) %>%
  dplyr::distinct(EntrezGeneSymbol, .keep_all = TRUE)

gene_module_assignment_tbl <- ensure_column(gene_module_assignment_tbl, "Protein_Name", NA_character_)
gene_module_assignment_tbl <- ensure_column(gene_module_assignment_tbl, "Protein_Display", NA_character_)
gene_module_assignment_tbl <- ensure_column(gene_module_assignment_tbl, "AptName", NA_character_)
gene_module_assignment_tbl <- ensure_column(gene_module_assignment_tbl, "SeqId", NA_character_)
gene_module_assignment_tbl <- ensure_column(gene_module_assignment_tbl, "EntrezGeneID", NA_character_)
gene_module_assignment_tbl <- ensure_column(gene_module_assignment_tbl, "TargetFullName", NA_character_)
gene_module_assignment_tbl <- ensure_column(gene_module_assignment_tbl, "Target", NA_character_)
gene_module_assignment_tbl <- ensure_column(gene_module_assignment_tbl, "UniProt", NA_character_)
gene_module_assignment_tbl <- ensure_column(gene_module_assignment_tbl, "N_genes", NA_real_)
gene_module_assignment_tbl <- ensure_column(gene_module_assignment_tbl, "Prop_total", NA_real_)

if (!"Representative_AptName" %in% names(gene_module_assignment_tbl)) {
  gene_module_assignment_tbl$Representative_AptName <- gene_module_assignment_tbl$AptName
}

gene_module_assignment_tbl <- gene_module_assignment_tbl %>%
  dplyr::mutate(
    Protein_Name = dplyr::coalesce(Protein_Name, EntrezGeneSymbol),
    Protein_Display = dplyr::coalesce(Protein_Display, Protein_Name, EntrezGeneSymbol),
    Representative_AptName = dplyr::coalesce(Representative_AptName, AptName)
  )

me_cols <- colnames(mergedMEs)
module_colors_from_MEs <- gsub("^ME", "", me_cols)

cat("Módulos detectados en mergedMEs:\n")
print(module_colors_from_MEs)

if (is.null(modules_of_interest)) {
  modules_of_interest <- setdiff(module_colors_from_MEs, exclude_modules)
} else {
  modules_of_interest <- modules_of_interest[
    modules_of_interest %in% module_colors_from_MEs
  ]
  modules_of_interest <- setdiff(modules_of_interest, exclude_modules)
}

if (length(modules_of_interest) == 0) {
  stop("No hay módulos válidos para analizar después de excluir módulos no deseados.", call. = FALSE)
}

cat("\nMódulos analizados en Script 03:\n")
print(modules_of_interest)
cat("\n")

###############################################################################
# 7) kME / MODULE MEMBERSHIP
###############################################################################

kME_mat <- WGCNA::signedKME(
  datExpr = datExpr_clean,
  datME = mergedMEs,
  exprWeights = NULL,
  MEWeights = NULL,
  outputColumnName = "kME",
  corFnc = "cor",
  corOptions = "use = 'pairwise.complete.obs'"
)

kME_tbl <- tibble::tibble(
  EntrezGeneSymbol = rownames(kME_mat)
) %>%
  dplyr::bind_cols(as.data.frame(kME_mat))

n_samples_kme <- nrow(datExpr_clean)

kME_long <- kME_tbl %>%
  tidyr::pivot_longer(
    cols = starts_with("kME"),
    names_to = "ME_col",
    values_to = "kME"
  ) %>%
  dplyr::mutate(
    Module_from_ME = gsub("^kME", "", ME_col),
    abs_kME = abs(kME)
  )

gene_module_small <- gene_module_assignment_tbl %>%
  dplyr::select(
    EntrezGeneSymbol,
    Module,
    Protein_Name,
    Protein_Display,
    Representative_AptName,
    AptName,
    SeqId,
    TargetFullName,
    Target,
    UniProt,
    EntrezGeneID,
    N_genes,
    Prop_total
  ) %>%
  dplyr::distinct()

kME_annot <- kME_long %>%
  dplyr::left_join(gene_module_small, by = "EntrezGeneSymbol") %>%
  dplyr::mutate(
    is_assigned_module = Module == Module_from_ME
  )

kME_assigned <- kME_annot %>%
  dplyr::filter(is_assigned_module) %>%
  dplyr::mutate(
    t_stat = kME * sqrt((n_samples_kme - 2) / pmax(1e-12, 1 - kME^2)),
    p_value = 2 * stats::pt(-abs(t_stat), df = n_samples_kme - 2)
  ) %>%
  dplyr::group_by(Module) %>%
  dplyr::mutate(
    FDR_within_module = p.adjust(p_value, method = "BH")
  ) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(Module, dplyr::desc(abs_kME), p_value)

safe_write_csv(
  kME_tbl,
  file.path(outdir, "tables", "full_kME_table_wide.csv")
)

safe_write_csv(
  kME_assigned,
  file.path(outdir, "tables", "full_kME_assigned_module_long.csv")
)

###############################################################################
# 8) HUB SUMMARY
###############################################################################

hub_summary <- kME_assigned %>%
  dplyr::group_by(Module) %>%
  dplyr::summarise(
    n_genes = dplyr::n(),
    mean_abs_kME = mean(abs_kME, na.rm = TRUE),
    median_abs_kME = median(abs_kME, na.rm = TRUE),
    max_abs_kME = max(abs_kME, na.rm = TRUE),
    n_hubs_abs_kME_ge_0_8 = sum(abs_kME >= 0.80, na.rm = TRUE),
    n_hubs_abs_kME_ge_0_7 = sum(abs_kME >= 0.70, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  dplyr::arrange(dplyr::desc(max_abs_kME))

safe_write_csv(
  hub_summary,
  file.path(outdir, "tables", "module_hub_summary.csv")
)

###############################################################################
# 9) TOP HUBS BY MODULE
###############################################################################

hub_tables <- list()

for (mod in modules_of_interest) {

  df_mod <- kME_assigned %>%
    dplyr::filter(Module == mod) %>%
    dplyr::arrange(dplyr::desc(abs_kME), p_value) %>%
    dplyr::mutate(
      hub_rank = dplyr::row_number()
    )

  if (nrow(df_mod) == 0) {
    message("Módulo sin genes asignados en kME_assigned: ", mod)
    next
  }

  n_top <- min(top_hubs_per_module, nrow(df_mod))
  top_mod <- head(df_mod, n_top)

  hub_tables[[mod]] <- top_mod

  safe_write_csv(
    df_mod,
    file.path(outdir, "hubs", paste0("all_hubs_ranked_", mod, ".csv"))
  )

  safe_write_csv(
    top_mod,
    file.path(outdir, "hubs", paste0("top_hubs_", mod, ".csv"))
  )

  plot_hub_bar(
    df_hubs = top_mod,
    module_name = mod,
    n_plot = top_plot_hubs,
    outdir_fig = file.path(outdir, "figures", "hubs")
  )
}

top_hubs_all_modules <- dplyr::bind_rows(hub_tables)

safe_write_csv(
  top_hubs_all_modules,
  file.path(outdir, "tables", "top_hubs_prioritized_modules_combined.csv")
)

###############################################################################
# 10) GENE ID MAPPING FOR ENRICHMENT
###############################################################################

gene_universe <- gene_module_assignment_tbl %>%
  dplyr::transmute(
    EntrezGeneSymbol = clean_text_na(EntrezGeneSymbol),
    EntrezGeneID = safe_numeric(EntrezGeneID)
  ) %>%
  dplyr::filter(
    !is.na(EntrezGeneSymbol),
    EntrezGeneSymbol != ""
  ) %>%
  dplyr::distinct()

symbol_to_entrez <- tryCatch(
  clusterProfiler::bitr(
    gene_universe$EntrezGeneSymbol,
    fromType = "SYMBOL",
    toType = "ENTREZID",
    OrgDb = org.Hs.eg.db
  ),
  error = function(e) {
    message("SYMBOL -> ENTREZID mapping failed: ", e$message)
    NULL
  }
)

if (is.null(symbol_to_entrez) || nrow(symbol_to_entrez) == 0) {

  if (all(is.na(gene_universe$EntrezGeneID))) {
    stop("No se pudo mapear SYMBOL -> ENTREZID y EntrezGeneID no está disponible.", call. = FALSE)
  }

  gene_universe_mapped <- gene_universe %>%
    dplyr::mutate(
      ENTREZID_final = as.character(EntrezGeneID)
    ) %>%
    dplyr::filter(!is.na(ENTREZID_final), ENTREZID_final != "") %>%
    dplyr::distinct(EntrezGeneSymbol, .keep_all = TRUE)

} else {

  gene_universe_mapped <- gene_universe %>%
    dplyr::left_join(
      symbol_to_entrez %>%
        dplyr::rename(
          EntrezGeneSymbol = SYMBOL,
          ENTREZID_map = ENTREZID
        ),
      by = "EntrezGeneSymbol"
    ) %>%
    dplyr::mutate(
      ENTREZID_final = dplyr::coalesce(
        as.character(EntrezGeneID),
        ENTREZID_map
      )
    ) %>%
    dplyr::filter(
      !is.na(ENTREZID_final),
      ENTREZID_final != ""
    ) %>%
    dplyr::distinct(EntrezGeneSymbol, .keep_all = TRUE)
}

background_entrez <- unique(gene_universe_mapped$ENTREZID_final)

if (length(background_entrez) < min_genes_for_enrichment) {
  stop("El universo de fondo mapeado para enrichment es demasiado pequeño.", call. = FALSE)
}

safe_write_csv(
  gene_universe_mapped,
  file.path(outdir, "tables", "gene_universe_symbol_to_entrez.csv")
)

###############################################################################
# 11) ENRICHMENT BY MODULE
###############################################################################

enrichment_summary <- list()
enrichment_errors <- list()

for (mod in modules_of_interest) {

  cat("\n============================\n")
  cat("Procesando módulo:", mod, "\n")
  cat("============================\n")

  module_genes <- gene_module_assignment_tbl %>%
    dplyr::filter(Module == mod) %>%
    dplyr::transmute(
      EntrezGeneSymbol = clean_text_na(EntrezGeneSymbol),
      Protein_Name = Protein_Name
    ) %>%
    dplyr::filter(
      !is.na(EntrezGeneSymbol),
      EntrezGeneSymbol != ""
    ) %>%
    dplyr::distinct()

  module_genes_mapped <- module_genes %>%
    dplyr::left_join(
      gene_universe_mapped %>%
        dplyr::select(EntrezGeneSymbol, ENTREZID_final),
      by = "EntrezGeneSymbol"
    ) %>%
    dplyr::filter(
      !is.na(ENTREZID_final),
      ENTREZID_final != ""
    ) %>%
    dplyr::distinct(EntrezGeneSymbol, .keep_all = TRUE)

  safe_write_csv(
    module_genes_mapped,
    file.path(outdir, "tables", paste0("genes_for_enrichment_", mod, ".csv"))
  )

  module_entrez <- unique(module_genes_mapped$ENTREZID_final)

  enrich_info <- tibble::tibble(
    Module = mod,
    n_symbols = nrow(module_genes),
    n_mapped_entrez = length(module_entrez),
    n_background = length(background_entrez)
  )

  safe_write_csv(
    enrich_info,
    file.path(outdir, "tables", paste0("enrichment_input_summary_", mod, ".csv"))
  )

  if (length(module_entrez) < min_genes_for_enrichment) {
    message("Módulo ", mod, " omitido en enrichment por pocos genes mapeados.")

    enrichment_summary[[mod]] <- tibble::tibble(
      Module = mod,
      n_symbols = nrow(module_genes),
      n_mapped_entrez = length(module_entrez),
      n_background = length(background_entrez),
      GO_BP_terms = 0,
      GO_BP_terms_fdr010 = 0,
      GO_BP_terms_total = 0,
      GO_BP_min_FDR = NA_real_,
      GO_BP_top_term = NA_character_,
      KEGG_terms = 0,
      KEGG_terms_fdr010 = 0,
      KEGG_terms_total = 0,
      KEGG_min_FDR = NA_real_,
      KEGG_top_term = NA_character_,
      Reactome_terms = 0,
      Reactome_terms_fdr010 = 0,
      Reactome_terms_total = 0,
      Reactome_min_FDR = NA_real_,
      Reactome_top_term = NA_character_
    )

    next
  }

  # -------------------------------------------------------------------------
  # GO Biological Process
  # -------------------------------------------------------------------------

  ego_bp <- tryCatch(
    clusterProfiler::enrichGO(
      gene = module_entrez,
      universe = background_entrez,
      OrgDb = org.Hs.eg.db,
      keyType = "ENTREZID",
      ont = "BP",
      pAdjustMethod = "BH",
      pvalueCutoff = enrich_retrieve_p_cutoff,
      qvalueCutoff = enrich_retrieve_q_cutoff,
      readable = TRUE
    ),
    error = function(e) {
      enrichment_errors[[paste(mod, "GO_BP", sep = "_")]] <<- tibble::tibble(
        Module = mod,
        Library = "GO_BP",
        Error = e$message
      )
      message("GO BP enrichment failed for module ", mod, ": ", e$message)
      NULL
    }
  )

  res_go <- save_enrichment_tables(
    res = ego_bp,
    module_name = mod,
    analysis_name = "GO_BP"
  )

  count_go <- make_enrich_count(res_go)

  # -------------------------------------------------------------------------
  # KEGG
  # -------------------------------------------------------------------------

  ekegg <- tryCatch(
    clusterProfiler::enrichKEGG(
      gene = module_entrez,
      universe = background_entrez,
      organism = "hsa",
      pAdjustMethod = "BH",
      pvalueCutoff = enrich_retrieve_p_cutoff,
      qvalueCutoff = enrich_retrieve_q_cutoff
    ),
    error = function(e) {
      enrichment_errors[[paste(mod, "KEGG", sep = "_")]] <<- tibble::tibble(
        Module = mod,
        Library = "KEGG",
        Error = e$message
      )
      message("KEGG enrichment failed for module ", mod, ": ", e$message)
      NULL
    }
  )

  res_kegg <- save_enrichment_tables(
    res = ekegg,
    module_name = mod,
    analysis_name = "KEGG"
  )

  count_kegg <- make_enrich_count(res_kegg)

  # -------------------------------------------------------------------------
  # Reactome
  # -------------------------------------------------------------------------

  ereact <- tryCatch(
    ReactomePA::enrichPathway(
      gene = module_entrez,
      universe = background_entrez,
      organism = "human",
      pvalueCutoff = enrich_retrieve_p_cutoff,
      pAdjustMethod = "BH",
      qvalueCutoff = enrich_retrieve_q_cutoff,
      readable = TRUE
    ),
    error = function(e) {
      enrichment_errors[[paste(mod, "Reactome", sep = "_")]] <<- tibble::tibble(
        Module = mod,
        Library = "Reactome",
        Error = e$message
      )
      message("Reactome enrichment failed for module ", mod, ": ", e$message)
      NULL
    }
  )

  res_react <- save_enrichment_tables(
    res = ereact,
    module_name = mod,
    analysis_name = "Reactome"
  )

  count_react <- make_enrich_count(res_react)

  enrichment_summary[[mod]] <- tibble::tibble(
    Module = mod,
    n_symbols = nrow(module_genes),
    n_mapped_entrez = length(module_entrez),
    n_background = length(background_entrez),

    GO_BP_terms = count_go$n_terms_fdr_0_05,
    GO_BP_terms_fdr010 = count_go$n_terms_fdr_0_10,
    GO_BP_terms_total = count_go$n_terms_total,
    GO_BP_min_FDR = count_go$min_FDR,
    GO_BP_top_term = count_go$top_term,

    KEGG_terms = count_kegg$n_terms_fdr_0_05,
    KEGG_terms_fdr010 = count_kegg$n_terms_fdr_0_10,
    KEGG_terms_total = count_kegg$n_terms_total,
    KEGG_min_FDR = count_kegg$min_FDR,
    KEGG_top_term = count_kegg$top_term,

    Reactome_terms = count_react$n_terms_fdr_0_05,
    Reactome_terms_fdr010 = count_react$n_terms_fdr_0_10,
    Reactome_terms_total = count_react$n_terms_total,
    Reactome_min_FDR = count_react$min_FDR,
    Reactome_top_term = count_react$top_term
  )
}

enrichment_summary_tbl <- dplyr::bind_rows(enrichment_summary)

safe_write_csv(
  enrichment_summary_tbl,
  file.path(outdir, "tables", "enrichment_summary_by_module.csv")
)

if (length(enrichment_errors) > 0) {
  enrichment_errors_tbl <- dplyr::bind_rows(enrichment_errors)
} else {
  enrichment_errors_tbl <- tibble::tibble(
    Module = character(),
    Library = character(),
    Error = character()
  )
}

safe_write_csv(
  enrichment_errors_tbl,
  file.path(outdir, "tables", "enrichment_errors_by_module.csv")
)

###############################################################################
# 12) OPTIONAL NETWORK TABLES
###############################################################################

for (mod in modules_of_interest) {

  if (!mod %in% names(hub_tables)) next

  node_tbl <- hub_tables[[mod]] %>%
    dplyr::mutate(
      node = EntrezGeneSymbol,
      label = dplyr::coalesce(
        Protein_Display,
        Protein_Name,
        EntrezGeneSymbol
      ),
      module = Module,
      module_color = get_module_color(Module),
      kME = kME,
      abs_kME = abs_kME,
      hub_rank = hub_rank
    ) %>%
    dplyr::select(
      node,
      label,
      module,
      module_color,
      kME,
      abs_kME,
      hub_rank,
      dplyr::everything()
    )

  safe_write_csv(
    node_tbl,
    file.path(outdir, "network_optional", paste0("nodes_top_hubs_", mod, ".csv"))
  )
}

###############################################################################
# 13) FINAL SUMMARY
###############################################################################

final_summary <- tibble::tibble(
  metric = c(
    "base_dir",
    "core_dir",
    "outdir",
    "wgcna_input_level",
    "n_samples_used_for_kME",
    "n_genes_in_datExpr_clean",
    "n_module_eigengenes",
    "n_prioritized_modules",
    "top_hubs_per_module_exported",
    "min_genes_for_enrichment",
    "n_background_entrez",
    "enrichment_retrieve_p_cutoff",
    "enrichment_retrieve_q_cutoff",
    "enrichment_sig_fdr_cutoff",
    "enrichment_suggestive_fdr_cutoff"
  ),
  value = c(
    base_dir,
    core_dir,
    outdir,
    "GENE-COLLAPSED, not aptamer-level",
    as.character(nrow(datExpr_clean)),
    as.character(ncol(datExpr_clean)),
    as.character(ncol(mergedMEs)),
    as.character(length(modules_of_interest)),
    as.character(top_hubs_per_module),
    as.character(min_genes_for_enrichment),
    as.character(length(background_entrez)),
    as.character(enrich_retrieve_p_cutoff),
    as.character(enrich_retrieve_q_cutoff),
    as.character(enrich_sig_fdr_cutoff),
    as.character(enrich_suggestive_fdr_cutoff)
  )
)

safe_write_csv(
  final_summary,
  file.path(outdir, "tables", "script3_final_summary.csv")
)

###############################################################################
# 14) SAVE WORKSPACE
###############################################################################

save(
  datExpr_clean,
  mergedMEs,
  gene_module_assignment_tbl,
  kME_tbl,
  kME_assigned,
  hub_summary,
  hub_tables,
  gene_universe_mapped,
  background_entrez,
  enrichment_summary_tbl,
  enrichment_errors_tbl,
  final_summary,
  file = file.path(outdir, "workspace", "script3_module_biology_workspace.RData")
)

writeLines(
  capture.output(utils::sessionInfo()),
  con = file.path(outdir, "sessionInfo.txt")
)

###############################################################################
# 15) FINAL MESSAGE
###############################################################################

cat("\nScript 03 terminado correctamente.\n")
cat("Directorio principal de salida:\n", outdir, "\n")
cat("Input level: GENE-COLLAPSED, not aptamer-level.\n")
cat("\nArchivos clave:\n")
cat("- tables/full_kME_assigned_module_long.csv\n")
cat("- tables/module_hub_summary.csv\n")
cat("- tables/enrichment_summary_by_module.csv\n")
cat("- tables/enrichment_errors_by_module.csv\n")
cat("- hubs/top_hubs_<module>.csv\n")
cat("- enrichment/GO_BP/*_all_terms.csv\n")
cat("- enrichment/KEGG/*_all_terms.csv\n")
cat("- enrichment/Reactome/*_all_terms.csv\n")
cat("- enrichment/significant/*_FDR005.csv\n")
cat("- enrichment/top_terms/*_top_terms.csv\n")
cat("- figures/hubs/*.pdf/png\n")
cat("- figures/enrichment/*.pdf/png\n")

###############################################################################
# END
###############################################################################

