###############################################################################
# 04b_WGCNA_country_categorical_reviewer_analysis.R
#
# PURPOSE
# Reviewer-facing WGCNA correction after Agustin's comments.
#
# This script DOES NOT rebuild WGCNA.
# It uses the module eigengenes and metadata already generated by Scripts 01–04
# and performs two reviewer-relevant corrections:
#
# 1) Removes Country_numeric from module-trait Spearman correlation outputs.
#    Country should not be treated as a numeric/ordinal trait because it is a
#    categorical recruitment-context variable.
#
# 2) Evaluates country and site/recruitment-context effects categorically:
#      - Kruskal-Wallis tests: module eigengene ~ Country
#      - Adjusted nested linear models:
#            module eigengene ~ Country + diagnosis + age + sex + education
#        compared against:
#            module eigengene ~ diagnosis + age + sex + education
#      - Optional analogous analyses for recruitment site, if detected.
#
# Interpretation:
# - These analyses are internal recruitment-context checks, not external
#   validation and not evidence of country-specific biology.
# - Use these outputs to revise Methods/Results and to remove Country_numeric
#   from module-trait figures/tables.
#
# Expected to be run after:
#   01_define_wgcna_input_from_DEP.R
#   02_wgcna_network_construction.R
#   04_WGCNA_module_trait_clinical_integration.R
#
# Main outputs:
#   results/04b_WGCNA_country_categorical_reviewer/
#     tables/module_trait_results_no_country_numeric.csv
#     tables/module_trait_correlations_no_country_numeric.csv
#     tables/module_trait_fdr_no_country_numeric.csv
#     tables/country_categorical_kruskal_by_module.csv
#     tables/country_categorical_adjusted_lm_by_module.csv
#     tables/country_module_descriptives.csv
#     tables/site_categorical_*.csv              [if site variable detected]
#     tables/reviewer_methods_wording.csv
#     figures/module_trait_heatmap_no_country_numeric.pdf/png
###############################################################################

rm(list = ls())

###############################################################################
# 00. Packages
###############################################################################

cran_pkgs <- c(
  "dplyr", "tidyr", "readr", "tibble", "stringr", "purrr",
  "ggplot2", "forcats", "openxlsx"
)

missing_pkgs <- cran_pkgs[!sapply(cran_pkgs, requireNamespace, quietly = TRUE)]
if (length(missing_pkgs) > 0) install.packages(missing_pkgs)

invisible(lapply(cran_pkgs, library, character.only = TRUE))

options(stringsAsFactors = FALSE)
options(error = traceback)

###############################################################################
# 01. Paths
###############################################################################

# Edit this only if your WGCNA folder is somewhere else.
BASE_DIR <- "C:/Users/mnpiz/Desktop/WGCNA_Workflow_april_V2"

SCRIPT1_DIR <- file.path(BASE_DIR, "results", "01_define_wgcna_input_from_DEP")
SCRIPT2_DIR <- file.path(BASE_DIR, "results", "02_WGCNA_core_collapsed_genes")
SCRIPT4_DIR <- file.path(BASE_DIR, "results", "04_WGCNA_module_trait_clinical_integration")

EIGENGENE_FILE <- file.path(
  SCRIPT2_DIR, "eigengenes", "module_eigengenes_per_sample.csv"
)

META_FILE <- file.path(
  SCRIPT1_DIR, "wgcna_sample_metadata.csv"
)

MODULE_TRAIT_FILE <- file.path(
  SCRIPT4_DIR, "tables", "module_trait_results_long.csv"
)

OUTDIR <- file.path(
  BASE_DIR, "results", "04b_WGCNA_country_categorical_reviewer"
)

OUT_TABLES <- file.path(OUTDIR, "tables")
OUT_FIGURES <- file.path(OUTDIR, "figures")

invisible(lapply(
  c(OUTDIR, OUT_TABLES, OUT_FIGURES),
  dir.create,
  recursive = TRUE,
  showWarnings = FALSE
))

###############################################################################
# 02. Parameters
###############################################################################

MIN_N_FOR_TEST <- 6

# Covariates for adjusted recruitment-context models.
# Diagnosis is included as SampleGroup_bin when available.
ADJUSTMENT_COVARS <- c("SampleGroup_bin", "Age", "Sex_bin", "Education")

# Main display order for module-trait heatmap without Country_numeric.
TRAIT_ORDER_NO_COUNTRY <- c(
  "SampleGroup_bin",
  "cdr_global",
  "cdr_boxscore",
  "mmse_total",
  "udsfaq_total",
  "NPI",
  "Mini_SEA",
  "T_ADLQ",
  "p_tau181",
  "p_tau217",
  "NfL",
  "ratio_AB42_40",
  "Age",
  "Sex_bin",
  "Education",
  "APOE4_carrier"
)

TRAIT_LABELS <- c(
  SampleGroup_bin = "Diagnosis",
  cdr_global = "CDR global",
  cdr_boxscore = "CDR-SB",
  mmse_total = "MMSE",
  udsfaq_total = "PFAQ",
  NPI = "NPI-Q",
  Mini_SEA = "Mini-SEA",
  T_ADLQ = "T-ADLQ",
  p_tau181 = "p-tau181",
  p_tau217 = "p-tau217",
  NfL = "NfL",
  ratio_AB42_40 = "Aβ42/40",
  Age = "Age",
  Sex_bin = "Sex",
  Education = "Education",
  APOE4_carrier = "APOE ε4"
)

MODULE_COLORS <- c(
  black       = "#2B2B2B",
  brown       = "#9C6B00",
  yellow      = "#B7D500",
  blue        = "#1535E8",
  green       = "#3E8F4E",
  red         = "#B4334A",
  purple      = "#8A2BE2",
  magenta     = "#C75ACD",
  pink        = "#F3A6D6",
  greenyellow = "#ADFF2F",
  grey        = "#9E9E9E"
)

###############################################################################
# 03. Helpers
###############################################################################

safe_read_csv <- function(file) {
  if (!file.exists(file)) {
    stop("Missing required file:\n", file, call. = FALSE)
  }
  readr::read_csv(file, show_col_types = FALSE)
}

safe_write_csv <- function(x, file) {
  dir.create(dirname(file), recursive = TRUE, showWarnings = FALSE)
  readr::write_csv(as_tibble(x), file)
}

clean_text_na <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x[x %in% c("", "NA", "NaN", "NULL", "null", "N/A", "nan")] <- NA_character_
  x
}

safe_numeric <- function(x) suppressWarnings(as.numeric(x))

standardize_module_name <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  gsub("^ME", "", x)
}

standardize_metadata_columns <- function(df) {
  rename_map <- c(
    "Mini-SEA" = "Mini_SEA",
    "Mini.SEA" = "Mini_SEA",
    "T-ADLQ" = "T_ADLQ",
    "T.ADLQ" = "T_ADLQ",
    "p-tau181" = "p_tau181",
    "p.tau181" = "p_tau181",
    "p-tau217" = "p_tau217",
    "p.tau217" = "p_tau217",
    "ratio AB42/40" = "ratio_AB42_40",
    "ratio.AB42.40" = "ratio_AB42_40"
  )

  for (old in names(rename_map)) {
    new <- rename_map[[old]]
    if (old %in% names(df) && !new %in% names(df)) {
      names(df)[names(df) == old] <- new
    }
  }

  df
}

encode_basic_variables <- function(df) {
  df <- df %>%
    dplyr::mutate(SampleId = as.character(SampleId))

  if ("SampleGroup" %in% names(df)) {
    df <- df %>%
      dplyr::mutate(
        SampleGroup = as.character(SampleGroup),
        SampleGroup_bin = dplyr::case_when(
          SampleGroup == "CN" ~ 0,
          SampleGroup == "AD" ~ 1,
          TRUE ~ NA_real_
        )
      )
  }

  if ("Sex" %in% names(df)) {
    df <- df %>%
      dplyr::mutate(
        Sex_chr = as.character(Sex),
        Sex_bin = dplyr::case_when(
          Sex_chr %in% c("1", "M", "Male", "male") ~ 0,
          Sex_chr %in% c("2", "F", "Female", "female") ~ 1,
          TRUE ~ safe_numeric(Sex_chr)
        )
      )
  }

  if ("ApoE" %in% names(df) && !"APOE_group" %in% names(df)) {
    df <- df %>%
      dplyr::mutate(
        ApoE = as.character(ApoE),
        APOE_group = dplyr::case_when(
          ApoE %in% c("e2/e4", "e3/e4", "e4/e4") ~ "E4 carrier",
          ApoE %in% c("e2/e2", "e2/e3", "e3/e3") ~ "Non-E4",
          TRUE ~ NA_character_
        )
      )
  }

  if ("APOE_group" %in% names(df) && !"APOE4_carrier" %in% names(df)) {
    df <- df %>%
      dplyr::mutate(
        APOE4_carrier = dplyr::case_when(
          APOE_group == "E4 carrier" ~ 1,
          APOE_group == "Non-E4" ~ 0,
          TRUE ~ NA_real_
        )
      )
  }

  numeric_candidates <- c(
    "Age", "Education", "cdr_global", "cdr_boxscore", "mmse_total",
    "udsfaq_total", "NPI", "Mini_SEA", "T_ADLQ", "p_tau181",
    "p_tau217", "NfL", "ratio_AB42_40", "APOE4_carrier",
    "SampleGroup_bin", "Sex_bin"
  )

  for (cc in intersect(numeric_candidates, names(df))) {
    df[[cc]] <- safe_numeric(df[[cc]])
  }

  # IMPORTANT:
  # We deliberately do NOT create Country_numeric here.
  # Country is kept as a categorical factor.
  if ("Country" %in% names(df)) {
    df <- df %>%
      dplyr::mutate(Country = factor(clean_text_na(Country)))
  }

  df
}

detect_site_variable <- function(df) {
  candidates <- c(
    "Site", "site", "Center", "center", "Cohort", "cohort",
    "RecruitmentSite", "recruitment_site", "site_id", "Site_ID"
  )
  hit <- candidates[candidates %in% names(df)][1]
  if (length(hit) == 0 || is.na(hit)) NA_character_ else hit
}

get_module_colors <- function(modules) {
  modules <- as.character(modules)
  cols <- MODULE_COLORS[modules]
  missing_mods <- modules[is.na(cols)]

  if (length(missing_mods) > 0) {
    extra_cols <- grDevices::rainbow(length(unique(missing_mods)), s = 0.45, v = 0.75)
    names(extra_cols) <- unique(missing_mods)
    cols[is.na(cols)] <- extra_cols[missing_mods]
  }

  names(cols) <- modules
  cols
}

add_sig_stars <- function(q) {
  dplyr::case_when(
    is.na(q) ~ "",
    q < 0.001 ~ "***",
    q < 0.01 ~ "**",
    q < 0.05 ~ "*",
    TRUE ~ ""
  )
}

safe_kruskal <- function(df, outcome, factor_var) {
  d <- df %>%
    dplyr::select(dplyr::all_of(c(outcome, factor_var))) %>%
    tidyr::drop_na()

  if (nrow(d) < MIN_N_FOR_TEST) {
    return(tibble(statistic = NA_real_, p_value = NA_real_, n = nrow(d), n_levels = NA_integer_))
  }

  d[[factor_var]] <- factor(d[[factor_var]])
  n_levels <- nlevels(d[[factor_var]])

  if (n_levels < 2) {
    return(tibble(statistic = NA_real_, p_value = NA_real_, n = nrow(d), n_levels = n_levels))
  }

  kt <- tryCatch(
    stats::kruskal.test(stats::as.formula(paste0(outcome, " ~ ", factor_var)), data = d),
    error = function(e) NULL
  )

  if (is.null(kt)) {
    return(tibble(statistic = NA_real_, p_value = NA_real_, n = nrow(d), n_levels = n_levels))
  }

  tibble(
    statistic = unname(kt$statistic),
    p_value = kt$p.value,
    n = nrow(d),
    n_levels = n_levels
  )
}

safe_adjusted_factor_lm <- function(df, outcome, factor_var, covars = ADJUSTMENT_COVARS) {
  available_covars <- covars[covars %in% names(df)]
  model_vars <- c(outcome, factor_var, available_covars)

  d <- df %>%
    dplyr::select(dplyr::all_of(model_vars)) %>%
    tidyr::drop_na()

  if (nrow(d) < MIN_N_FOR_TEST) {
    return(tibble(
      n = nrow(d),
      n_levels = NA_integer_,
      covariates = paste(available_covars, collapse = ", "),
      p_value_factor = NA_real_,
      partial_R2_factor = NA_real_,
      full_model_adj_R2 = NA_real_
    ))
  }

  d[[factor_var]] <- factor(d[[factor_var]])
  n_levels <- nlevels(d[[factor_var]])

  if (n_levels < 2) {
    return(tibble(
      n = nrow(d),
      n_levels = n_levels,
      covariates = paste(available_covars, collapse = ", "),
      p_value_factor = NA_real_,
      partial_R2_factor = NA_real_,
      full_model_adj_R2 = NA_real_
    ))
  }

  rhs_full <- paste(c(factor_var, available_covars), collapse = " + ")
  rhs_reduced <- if (length(available_covars) > 0) paste(available_covars, collapse = " + ") else "1"

  form_full <- stats::as.formula(paste0(outcome, " ~ ", rhs_full))
  form_reduced <- stats::as.formula(paste0(outcome, " ~ ", rhs_reduced))

  fit_full <- tryCatch(stats::lm(form_full, data = d), error = function(e) NULL)
  fit_reduced <- tryCatch(stats::lm(form_reduced, data = d), error = function(e) NULL)

  if (is.null(fit_full) || is.null(fit_reduced)) {
    return(tibble(
      n = nrow(d),
      n_levels = n_levels,
      covariates = paste(available_covars, collapse = ", "),
      p_value_factor = NA_real_,
      partial_R2_factor = NA_real_,
      full_model_adj_R2 = NA_real_
    ))
  }

  cmp <- tryCatch(stats::anova(fit_reduced, fit_full), error = function(e) NULL)

  if (is.null(cmp) || nrow(cmp) < 2) {
    p_val <- NA_real_
    partial_r2 <- NA_real_
  } else {
    p_val <- cmp$`Pr(>F)`[2]
    rss_reduced <- cmp$RSS[1]
    rss_full <- cmp$RSS[2]
    partial_r2 <- (rss_reduced - rss_full) / rss_reduced
  }

  tibble(
    n = nrow(d),
    n_levels = n_levels,
    covariates = paste(available_covars, collapse = ", "),
    p_value_factor = p_val,
    partial_R2_factor = partial_r2,
    full_model_adj_R2 = summary(fit_full)$adj.r.squared
  )
}

make_factor_descriptives <- function(df, modules, factor_var) {
  purrr::map_dfr(modules, function(m) {
    df %>%
      dplyr::select(dplyr::all_of(c(m, factor_var))) %>%
      tidyr::drop_na() %>%
      dplyr::mutate(Level = as.character(.data[[factor_var]])) %>%
      dplyr::group_by(Level) %>%
      dplyr::summarise(
        Module = m,
        n = dplyr::n(),
        mean_eigengene = mean(.data[[m]], na.rm = TRUE),
        sd_eigengene = sd(.data[[m]], na.rm = TRUE),
        median_eigengene = median(.data[[m]], na.rm = TRUE),
        q25_eigengene = quantile(.data[[m]], 0.25, na.rm = TRUE),
        q75_eigengene = quantile(.data[[m]], 0.75, na.rm = TRUE),
        .groups = "drop"
      ) %>%
      dplyr::select(Module, Level, dplyr::everything())
  })
}

###############################################################################
# 04. Load data
###############################################################################

eig <- safe_read_csv(EIGENGENE_FILE)
meta <- safe_read_csv(META_FILE)

module_trait_original <- if (file.exists(MODULE_TRAIT_FILE)) {
  safe_read_csv(MODULE_TRAIT_FILE)
} else {
  NULL
}

eig <- eig %>%
  dplyr::mutate(SampleId = as.character(SampleId)) %>%
  dplyr::distinct(SampleId, .keep_all = TRUE)

meta <- meta %>%
  standardize_metadata_columns() %>%
  encode_basic_variables() %>%
  dplyr::distinct(SampleId, .keep_all = TRUE)

eig_cols_original <- setdiff(names(eig), "SampleId")
eig_cols_original <- eig_cols_original[!eig_cols_original %in% c("MEgrey", "grey")]

eig_clean <- eig
names(eig_clean)[names(eig_clean) %in% eig_cols_original] <- standardize_module_name(eig_cols_original)

module_cols <- setdiff(names(eig_clean), "SampleId")
module_cols <- module_cols[vapply(eig_clean[module_cols], is.numeric, logical(1))]
module_cols <- setdiff(module_cols, "grey")

analysis_df <- eig_clean %>%
  dplyr::inner_join(meta, by = "SampleId")

for (m in module_cols) {
  analysis_df[[m]] <- safe_numeric(analysis_df[[m]])
}

if (!"Country" %in% names(analysis_df)) {
  stop("Country variable was not found in metadata. Cannot run country categorical analysis.", call. = FALSE)
}

site_var <- detect_site_variable(analysis_df)

safe_write_csv(
  analysis_df,
  file.path(OUT_TABLES, "wgcna_country_categorical_input_clean.csv")
)

###############################################################################
# 05. Remove Country_numeric from module-trait correlation outputs
###############################################################################

if (!is.null(module_trait_original)) {
  module_trait_no_country <- module_trait_original %>%
    dplyr::filter(!Trait %in% c("Country_numeric", "country_numeric", "Country")) %>%
    dplyr::mutate(
      FDR = p.adjust(p_value, method = "BH"),
      stars = add_sig_stars(FDR),
      Trait_label = dplyr::recode(Trait, !!!TRAIT_LABELS, .default = Trait)
    )

  safe_write_csv(
    module_trait_no_country,
    file.path(OUT_TABLES, "module_trait_results_no_country_numeric.csv")
  )

  rho_no_country <- module_trait_no_country %>%
    dplyr::select(Module, Trait, rho) %>%
    tidyr::pivot_wider(names_from = Trait, values_from = rho) %>%
    dplyr::arrange(factor(Module, levels = unique(Module)))

  fdr_no_country <- module_trait_no_country %>%
    dplyr::select(Module, Trait, FDR) %>%
    tidyr::pivot_wider(names_from = Trait, values_from = FDR) %>%
    dplyr::arrange(factor(Module, levels = unique(Module)))

  annot_no_country <- module_trait_no_country %>%
    dplyr::select(Module, Trait, stars) %>%
    tidyr::pivot_wider(names_from = Trait, values_from = stars) %>%
    dplyr::arrange(factor(Module, levels = unique(Module)))

  safe_write_csv(
    rho_no_country,
    file.path(OUT_TABLES, "module_trait_correlations_no_country_numeric.csv")
  )

  safe_write_csv(
    fdr_no_country,
    file.path(OUT_TABLES, "module_trait_fdr_no_country_numeric.csv")
  )

  safe_write_csv(
    annot_no_country,
    file.path(OUT_TABLES, "module_trait_annotations_no_country_numeric.csv")
  )

  # Simple ggplot heatmap without country for reviewer/documentation.
  heatmap_df <- module_trait_no_country %>%
    dplyr::filter(Trait %in% TRAIT_ORDER_NO_COUNTRY) %>%
    dplyr::mutate(
      Trait = factor(Trait, levels = TRAIT_ORDER_NO_COUNTRY),
      Trait_label = dplyr::recode(as.character(Trait), !!!TRAIT_LABELS, .default = as.character(Trait)),
      Trait_label = factor(Trait_label, levels = unname(TRAIT_LABELS[TRAIT_ORDER_NO_COUNTRY[TRAIT_ORDER_NO_COUNTRY %in% names(TRAIT_LABELS)]])),
      Module = factor(Module, levels = unique(Module))
    )

  p_heat <- ggplot2::ggplot(
    heatmap_df,
    ggplot2::aes(x = Trait_label, y = Module, fill = rho)
  ) +
    ggplot2::geom_tile(color = "grey90", linewidth = 0.25) +
    ggplot2::geom_text(ggplot2::aes(label = stars), size = 3) +
    ggplot2::scale_fill_gradient2(
      low = "#6FA8DC",
      mid = "white",
      high = "#F4A08B",
      midpoint = 0,
      limits = c(-0.35, 0.35),
      oob = scales::squish,
      name = "Spearman rho"
    ) +
    ggplot2::labs(
      title = "WGCNA module–trait associations without numerically encoded country",
      x = NULL,
      y = "Module"
    ) +
    ggplot2::theme_bw(base_size = 10) +
    ggplot2::theme(
      panel.grid = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1),
      plot.title = ggplot2::element_text(face = "bold")
    )

  ggplot2::ggsave(
    file.path(OUT_FIGURES, "module_trait_heatmap_no_country_numeric.pdf"),
    p_heat,
    width = 9.5,
    height = 5.5,
    device = grDevices::cairo_pdf
  )

  ggplot2::ggsave(
    file.path(OUT_FIGURES, "module_trait_heatmap_no_country_numeric.png"),
    p_heat,
    width = 9.5,
    height = 5.5,
    dpi = 600,
    bg = "white"
  )
}

###############################################################################
# 06. Country as categorical recruitment-context variable
###############################################################################

country_kruskal <- purrr::map_dfr(module_cols, function(m) {
  safe_kruskal(analysis_df, outcome = m, factor_var = "Country") %>%
    dplyr::mutate(Module = m, factor = "Country", .before = 1)
}) %>%
  dplyr::mutate(FDR = p.adjust(p_value, method = "BH"))

country_lm <- purrr::map_dfr(module_cols, function(m) {
  safe_adjusted_factor_lm(analysis_df, outcome = m, factor_var = "Country") %>%
    dplyr::mutate(Module = m, factor = "Country", .before = 1)
}) %>%
  dplyr::mutate(FDR_factor = p.adjust(p_value_factor, method = "BH"))

country_descriptives <- make_factor_descriptives(
  analysis_df,
  modules = module_cols,
  factor_var = "Country"
) %>%
  dplyr::rename(Country = Level)

safe_write_csv(
  country_kruskal,
  file.path(OUT_TABLES, "country_categorical_kruskal_by_module.csv")
)

safe_write_csv(
  country_lm,
  file.path(OUT_TABLES, "country_categorical_adjusted_lm_by_module.csv")
)

safe_write_csv(
  country_descriptives,
  file.path(OUT_TABLES, "country_module_descriptives.csv")
)

###############################################################################
# 07. Optional recruitment-site categorical analysis
###############################################################################

site_kruskal <- tibble()
site_lm <- tibble()
site_descriptives <- tibble()

if (!is.na(site_var) && site_var %in% names(analysis_df)) {
  analysis_df[[site_var]] <- factor(clean_text_na(analysis_df[[site_var]]))

  site_kruskal <- purrr::map_dfr(module_cols, function(m) {
    safe_kruskal(analysis_df, outcome = m, factor_var = site_var) %>%
      dplyr::mutate(Module = m, factor = site_var, .before = 1)
  }) %>%
    dplyr::mutate(FDR = p.adjust(p_value, method = "BH"))

  site_lm <- purrr::map_dfr(module_cols, function(m) {
    safe_adjusted_factor_lm(analysis_df, outcome = m, factor_var = site_var) %>%
      dplyr::mutate(Module = m, factor = site_var, .before = 1)
  }) %>%
    dplyr::mutate(FDR_factor = p.adjust(p_value_factor, method = "BH"))

  site_descriptives <- make_factor_descriptives(
    analysis_df,
    modules = module_cols,
    factor_var = site_var
  ) %>%
    dplyr::rename(Site = Level)

  safe_write_csv(
    site_kruskal,
    file.path(OUT_TABLES, "site_categorical_kruskal_by_module.csv")
  )

  safe_write_csv(
    site_lm,
    file.path(OUT_TABLES, "site_categorical_adjusted_lm_by_module.csv")
  )

  safe_write_csv(
    site_descriptives,
    file.path(OUT_TABLES, "site_module_descriptives.csv")
  )
}

###############################################################################
# 08. Manuscript-facing notes and methods wording
###############################################################################

reviewer_methods_wording <- tibble::tribble(
  ~section, ~text,
  "Methods - module-trait correlations",
  "Country was not included as a numerically encoded variable in Spearman module–trait correlation matrices because it is a categorical recruitment-context variable rather than an ordinal trait. Module–trait correlations therefore included clinical, cognitive, demographic, genetic and plasma biomarker variables suitable for rank-based correlation analyses.",

  "Methods - recruitment context",
  "Recruitment-context effects were evaluated separately by treating country, and recruitment site when available, as categorical factors. For each module eigengene, we used Kruskal-Wallis tests to compare module eigengene distributions across countries and adjusted nested linear models to quantify country-level variance after accounting for diagnosis, age, sex and education.",

  "Interpretation",
  "Country- and site-level analyses were interpreted as internal recruitment-context sensitivity analyses rather than as evidence of country-specific biology or external validation."
)

safe_write_csv(
  reviewer_methods_wording,
  file.path(OUT_TABLES, "reviewer_methods_wording.csv")
)

analysis_summary <- tibble::tibble(
  item = c(
    "n_samples",
    "n_modules",
    "modules",
    "country_levels",
    "site_variable_detected",
    "site_levels",
    "removed_from_spearman_matrix"
  ),
  value = c(
    as.character(nrow(analysis_df)),
    as.character(length(module_cols)),
    paste(module_cols, collapse = ", "),
    paste(levels(droplevels(analysis_df$Country)), collapse = ", "),
    ifelse(is.na(site_var), "No", site_var),
    ifelse(is.na(site_var), "Not available", paste(levels(droplevels(factor(analysis_df[[site_var]]))), collapse = ", ")),
    "Country_numeric"
  )
)

safe_write_csv(
  analysis_summary,
  file.path(OUT_TABLES, "wgcna_country_categorical_analysis_summary.csv")
)

###############################################################################
# 09. Integrated Excel workbook
###############################################################################

wb_file <- file.path(OUTDIR, "WGCNA_Country_Categorical_Reviewer_Analysis.xlsx")

tables_for_excel <- list(
  Analysis_summary = analysis_summary,
  Methods_wording = reviewer_methods_wording,
  Country_Kruskal = country_kruskal,
  Country_Adjusted_LM = country_lm,
  Country_Descriptives = country_descriptives,
  Site_Kruskal = site_kruskal,
  Site_Adjusted_LM = site_lm,
  Site_Descriptives = site_descriptives
)

if (!is.null(module_trait_original)) {
  tables_for_excel$ModuleTrait_NoCountryNumeric <- module_trait_no_country
}

openxlsx::write.xlsx(
  tables_for_excel,
  file = wb_file,
  overwrite = TRUE
)

message("Done.")
message("Outputs saved to: ", OUTDIR)
message("Main workbook: ", wb_file)
message("Country was treated as categorical; Country_numeric was removed from Spearman module-trait outputs.")
###############################################################################
# END
###############################################################################
