###############################################################################
# 06_6_wgcna_figure3_main_NatureAging_balanced_panels.R
#
# TITLE:
# Main WGCNA Figure 3 assembly using gene-collapsed modules - balanced Nature Aging layout
#
# PURPOSE:
# Generate a revised main WGCNA Figure 3 from outputs generated by Scripts 02–04.
# This v6.2 version preserves the Federica-aligned structure and adds editorial polish:
#   1) Remove DEP-direction from the WGCNA module portraits because module
#      membership is based on signed co-expression structure, not DEP direction.
#   2) Keep black in the module-trait and prioritization panels, but do not
#      force black into the hub/enrichment portraits because black has no
#      significant pathway enrichment in the current outputs.
#   3) Show only hub network + significant pathway enrichment for the
#      biologically interpretable portraits.
#   4) Improve journal-level visual style: cleaner TOM networks, at least
#      eight labelled hubs, softer edges, abbreviated pathway labels, larger
#      panel letters, and more compact layout.
#
# IMPORTANT:
# Adapted to:
#   C:/Users/mnpiz/Desktop/WGCNA_Workflow_april_V2
#
# Core modules for trait/prioritization visualization:
#   black, brown, yellow
#
# Core modules for biological portraits:
#   brown, yellow
#
# Black is retained in heatmap/prioritization but excluded from the biological
# portrait because enrichment_summary_by_module shows 0 significant GO/KEGG/Reactome
# terms for black.
#
# WGCNA level:
#   GENE-COLLAPSED, not aptamer-level.
###############################################################################

rm(list = ls())

##############################################################################
# 1) PACKAGES
##############################################################################

cran_pkgs <- c(
  "dplyr",
  "readr",
  "stringr",
  "ggplot2",
  "forcats",
  "tidyr",
  "purrr",
  "patchwork",
  "cowplot",
  "scales",
  "pdftools",
  "png",
  "grid",
  "tibble",
  "igraph",
  "ggraph",
  "graphlayouts",
  "tidygraph",
  "ggrepel"
)

cran_missing <- cran_pkgs[!sapply(cran_pkgs, requireNamespace, quietly = TRUE)]

if (length(cran_missing) > 0) {
  install.packages(cran_missing)
}

invisible(lapply(cran_pkgs, library, character.only = TRUE))

options(stringsAsFactors = FALSE)
options(error = traceback)

##############################################################################
# 2) FIGURE STANDARDS
##############################################################################

BASE_FONT_FAMILY  <- "Arial"
BASE_FONT_SIZE    <- 10
TITLE_SIZE        <- 12
SUBTITLE_SIZE     <- 9.5
AXIS_TITLE_SIZE   <- 10
AXIS_TEXT_SIZE    <- 9
STRIP_TEXT_SIZE   <- 9.5
LEGEND_TITLE_SIZE <- 9.5
LEGEND_TEXT_SIZE  <- 9

LINE_WIDTH_BASE <- 0.45
POINT_SIZE_BASE <- 1.8

COL_UP      <- "#f46d43"
COL_DOWN    <- "#4682b4"
COL_NEUTRAL <- "grey70"
COL_NS      <- "grey78"
COL_TEXT    <- "black"
COL_BORDER  <- "grey80"
COL_GRID    <- "grey90"
COL_TRACK   <- "grey92"

FIG_DIMS <- list(
  square_small  = c(6, 5),
  square_medium = c(6.5, 6.5),
  wide_medium   = c(8, 5),
  wide_large    = c(10, 6),
  panel_grid    = c(12, 8),
  panel_2col    = c(16, 8.5),
  tall_pathway  = c(8, 12),
  heatmap_wide  = c(10, 5),
  forest_medium = c(7, 5)
)

theme_pub <- function(base_size = BASE_FONT_SIZE, base_family = BASE_FONT_FAMILY) {
  ggplot2::theme_bw(base_size = base_size, base_family = base_family) +
    ggplot2::theme(
      panel.grid.major = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      panel.border = ggplot2::element_rect(linewidth = LINE_WIDTH_BASE, color = COL_TEXT),
      axis.line = ggplot2::element_line(linewidth = LINE_WIDTH_BASE, color = COL_TEXT),
      axis.ticks = ggplot2::element_line(linewidth = LINE_WIDTH_BASE, color = COL_TEXT),
      axis.title = ggplot2::element_text(size = AXIS_TITLE_SIZE, color = COL_TEXT),
      axis.text = ggplot2::element_text(size = AXIS_TEXT_SIZE, color = COL_TEXT),
      plot.title = ggplot2::element_text(size = TITLE_SIZE, face = "bold", hjust = 0.5, color = COL_TEXT),
      plot.subtitle = ggplot2::element_text(size = SUBTITLE_SIZE, hjust = 0.5, color = COL_TEXT),
      strip.background = ggplot2::element_rect(fill = "white", color = COL_TEXT, linewidth = LINE_WIDTH_BASE),
      strip.text = ggplot2::element_text(size = STRIP_TEXT_SIZE, face = "bold", color = COL_TEXT),
      legend.title = ggplot2::element_text(size = LEGEND_TITLE_SIZE, color = COL_TEXT),
      legend.text = ggplot2::element_text(size = LEGEND_TEXT_SIZE, color = COL_TEXT),
      legend.key = ggplot2::element_blank(),
      plot.margin = ggplot2::margin(10, 10, 10, 10)
    )
}

theme_card <- function(base_size = 11, base_family = BASE_FONT_FAMILY) {
  ggplot2::theme_minimal(base_size = base_size, base_family = base_family) +
    ggplot2::theme(
      panel.grid.major = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      panel.border = ggplot2::element_rect(color = COL_BORDER, fill = NA, linewidth = 0.6),
      axis.line = ggplot2::element_blank(),
      axis.ticks = ggplot2::element_blank(),
      axis.title = ggplot2::element_text(size = 11, color = COL_TEXT),
      axis.text = ggplot2::element_text(size = 10, color = COL_TEXT),
      plot.title = ggplot2::element_text(size = 12, face = "bold", hjust = 0, color = COL_TEXT),
      plot.subtitle = ggplot2::element_text(size = 10, hjust = 0, color = "grey35"),
      plot.margin = ggplot2::margin(8, 8, 8, 8),
      legend.position = "none"
    )
}

theme_void_card <- function(base_size = 11, base_family = BASE_FONT_FAMILY) {
  ggplot2::theme_void(base_size = base_size, base_family = base_family) +
    ggplot2::theme(
      panel.border = ggplot2::element_rect(color = COL_BORDER, fill = NA, linewidth = 0.6),
      plot.title = ggplot2::element_text(size = 12, face = "bold", hjust = 0, color = COL_TEXT),
      plot.subtitle = ggplot2::element_text(size = 10, hjust = 0, color = "grey35"),
      plot.margin = ggplot2::margin(8, 8, 8, 8)
    )
}

save_pub_pdf <- function(plot_obj, filename, dims = FIG_DIMS$wide_medium) {
  ggplot2::ggsave(
    filename = filename,
    plot = plot_obj,
    width = dims[1],
    height = dims[2],
    units = "in",
    device = grDevices::cairo_pdf,
    dpi = 300,
    bg = "white",
    limitsize = FALSE
  )
}

save_pub_png <- function(plot_obj, filename, dims = FIG_DIMS$wide_medium) {
  ggplot2::ggsave(
    filename = filename,
    plot = plot_obj,
    width = dims[1],
    height = dims[2],
    units = "in",
    dpi = 600,
    bg = "white",
    limitsize = FALSE
  )
}

save_pub_both <- function(plot_obj, filename_base, dims = FIG_DIMS$wide_medium) {
  save_pub_pdf(plot_obj, paste0(filename_base, ".pdf"), dims = dims)
  save_pub_png(plot_obj, paste0(filename_base, ".png"), dims = dims)
}

##############################################################################
# 3) PATHS
##############################################################################

BASE_DIR <- "C:/Users/mnpiz/Desktop/WGCNA_Workflow_april_V2"
DEP_PROJECT_ROOT <- "C:/Users/mnpiz/Desktop/DEPs_Proteomic_Publishable_V2"

SCRIPT2_DIR <- file.path(BASE_DIR, "results", "02_WGCNA_core_collapsed_genes")
SCRIPT3_DIR <- file.path(BASE_DIR, "results", "03_WGCNA_module_biology_hubs_enrichment")
SCRIPT4_DIR <- file.path(BASE_DIR, "results", "04_WGCNA_module_trait_clinical_integration")

OUTDIR <- file.path(BASE_DIR, "results", "06_8_wgcna_figure3_main_FINAL_bugfix")
OUTDIR_PANELS <- file.path(OUTDIR, "separate_panels")
OUTDIR_SUPP   <- file.path(OUTDIR, "supplementary")
OUTDIR_TABLES <- file.path(OUTDIR, "tables")

dir.create(OUTDIR, recursive = TRUE, showWarnings = FALSE)
dir.create(OUTDIR_PANELS, recursive = TRUE, showWarnings = FALSE)
dir.create(OUTDIR_SUPP, recursive = TRUE, showWarnings = FALSE)
dir.create(OUTDIR_TABLES, recursive = TRUE, showWarnings = FALSE)

# Script 2
DENDRO_PDF         <- file.path(SCRIPT2_DIR, "modules", "merged_modules_dendrogram.pdf")
DENDRO_PNG         <- file.path(OUTDIR, "tmp_panel_a_dendrogram.png")
MODULE_COUNT_FILE  <- file.path(SCRIPT2_DIR, "tables", "module_counts.csv")
GENE_MODULE_FILE   <- file.path(SCRIPT2_DIR, "tables", "gene_module_assignment.csv")
WORKSPACE_FILE     <- file.path(SCRIPT2_DIR, "workspace", "wgcna_core_collapsed_workspace.RData")

# Script 3
HUB_DIR            <- file.path(SCRIPT3_DIR, "hubs")
ENRICH_GO_DIR      <- file.path(SCRIPT3_DIR, "enrichment", "GO_BP")
ENRICH_KEGG_DIR    <- file.path(SCRIPT3_DIR, "enrichment", "KEGG")
ENRICH_REACT_DIR   <- file.path(SCRIPT3_DIR, "enrichment", "Reactome")

# Script 4
MODULE_TRAIT_LONG_FILE  <- file.path(SCRIPT4_DIR, "tables", "module_trait_results_long.csv")
PRIORITIZATION_FILE     <- file.path(SCRIPT4_DIR, "tables", "final_module_prioritization_table.csv")
MODULE_DEP_SUMMARY_FILE <- file.path(SCRIPT4_DIR, "tables", "module_dep_summary.csv")

# DEP full gene-collapsed results
DEP_RESULTS_FILE <- file.path(
  DEP_PROJECT_ROOT,
  "result",
  "03_dep",
  "gene_collapsed",
  "AD_vs_CN_full_limma_results_gene_collapsed.csv"
)

##############################################################################
# 4) PARAMETERS
##############################################################################

TOP_MODULES_HEATMAP <- c("black", "brown", "yellow")

# Federica-aligned portrait logic:
# black remains in the heatmap and prioritization panel, but is not forced into
# the portrait panel because it has no significant enrichment.
TOP_MODULES_NETWORK_MAIN <- c("brown", "yellow")
TOP_MODULES_NETWORK <- TOP_MODULES_NETWORK_MAIN

TOP_HUBS_N            <- 18
N_SEED_HUBS           <- 8
N_NEIGHBORS_PER_HUB   <- 2
LABEL_TOP_NODES       <- 8
TOP_PATHWAYS_N        <- 5
MAX_TERMS_PER_LIBRARY <- 2

EDGE_TOM_THRESHOLD    <- 0.010
MIN_EDGES_IF_SPARSE   <- 24
MAX_EDGES_TO_PLOT     <- 45
DEP_FDR_CUTOFF        <- 0.05

DISPLAY_MODULE_INTERNAL_NAME <- TRUE

TRAITS_MAIN <- c(
  "SampleGroup_bin",
  "cdr_boxscore",
  "mmse_total",
  "udsfaq_total",
  "p_tau181",
  "p_tau217",
  "NfL",
  "ratio_AB42_40",
  "Age",
  "Sex_bin",
  "Education",
  "APOE4_carrier"
)

TRAIT_LABELS <- c(
  SampleGroup_bin = "Diagnosis",
  cdr_boxscore    = "CDR-SB",
  mmse_total      = "MMSE",
  udsfaq_total    = "PFAQ",
  p_tau181        = "p-tau181",
  p_tau217        = "p-tau217",
  NfL             = "NfL",
  ratio_AB42_40   = "Aβ42/40",
  Age             = "Age",
  Sex_bin         = "Sex",
  Education       = "Education",
  APOE4_carrier   = "APOE ε4"
)

MODULE_COLORS <- c(
  black       = "#2B2B2B",
  brown       = "#9C6B00",
  yellow      = "#B7D500",
  blue        = "#1535E8",
  green       = "#3E8F4E",
  red         = "#B4334A",
  purple      = "#8A2BE2",
  magenta     = "#C75ACD",
  pink        = "#F3A6D6",
  greenyellow = "#ADFF2F",
  grey        = "#9E9E9E",
  other       = "grey85"
)

LIBRARY_COLORS <- c(
  GO_BP    = "#8DA0CB",
  Reactome = "#66C2A5",
  KEGG     = "#FC8D62"
)

##############################################################################
# 5) HELPERS
##############################################################################

safe_read_csv <- function(file) {
  if (!file.exists(file)) stop("No existe el archivo:\n", file, call. = FALSE)
  readr::read_csv(file, show_col_types = FALSE)
}

safe_write_csv <- function(x, file) {
  dir.create(dirname(file), recursive = TRUE, showWarnings = FALSE)
  readr::write_csv(x, file)
}

clean_text_na <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x[x %in% c("", "NA", "NaN", "NULL", "null", "N/A", "nan")] <- NA_character_
  x
}

safe_numeric <- function(x) {
  suppressWarnings(as.numeric(x))
}

standardize_module_name <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  gsub("^ME", "", x)
}

add_sig_stars <- function(q) {
  dplyr::case_when(
    is.na(q)  ~ "",
    q < 0.001 ~ "***",
    q < 0.01  ~ "**",
    q < 0.05  ~ "*",
    TRUE      ~ ""
  )
}

make_module_display_labels <- function(modules, show_internal_name = TRUE) {
  modules <- as.character(modules)
  if (show_internal_name) {
    labels <- paste0("M", seq_along(modules), " / ", modules)
  } else {
    labels <- paste0("M", seq_along(modules))
  }
  stats::setNames(labels, modules)
}

convert_pdf_first_page_to_png <- function(pdf_file, png_file, dpi = 300) {
  if (!file.exists(pdf_file)) stop("No existe el PDF del dendrograma:\n", pdf_file, call. = FALSE)

  tmp_pattern <- file.path(dirname(png_file), "tmp_dendro_page_%d.png")

  out_files <- suppressWarnings(
    pdftools::pdf_convert(
      pdf = pdf_file,
      format = "png",
      pages = 1,
      filenames = tmp_pattern,
      dpi = dpi
    )
  )

  if (length(out_files) == 0 || !file.exists(out_files[1])) {
    stop("No se pudo convertir el PDF del dendrograma a PNG.", call. = FALSE)
  }

  file.copy(out_files[1], png_file, overwrite = TRUE)
  invisible(png_file)
}

panel_from_png <- function(png_file, crop_white = TRUE, pad_px = 18) {
  if (!file.exists(png_file)) stop("No existe el PNG esperado:\n", png_file, call. = FALSE)

  img <- png::readPNG(png_file)

  # Editorial fix for panel a:
  # the WGCNA dendrogram PDF often carries large white margins, making panel a
  # look visually smaller than panels b-d. We crop near-white margins before
  # placing it in the composite so panels a-d occupy comparable visual space.
  if (crop_white) {
    rgb <- img[, , seq_len(min(3, dim(img)[3])), drop = FALSE]
    nonwhite <- apply(rgb < 0.985, c(1, 2), any)
    if (any(nonwhite)) {
      rr <- range(which(rowSums(nonwhite) > 0))
      cc <- range(which(colSums(nonwhite) > 0))
      rr <- pmax(1, c(rr[1] - pad_px, rr[2] + pad_px))
      cc <- pmax(1, c(cc[1] - pad_px, cc[2] + pad_px))
      rr[2] <- min(dim(img)[1], rr[2])
      cc[2] <- min(dim(img)[2], cc[2])
      img <- img[rr[1]:rr[2], cc[1]:cc[2], , drop = FALSE]
    }
  }

  cowplot::ggdraw() +
    cowplot::draw_image(img, x = 0.5, y = 0.5, hjust = 0.5, vjust = 0.5, scale = 0.98) +
    theme(
      plot.margin = margin(2, 2, 2, 2),
      plot.background = element_rect(fill = "white", color = NA)
    )
}

blank_placeholder <- function(title = "No data available", subtitle = NULL) {
  p <- ggplot() +
    annotate("text", x = 0.5, y = 0.58, label = title, size = 5, fontface = "bold") +
    coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
    theme_void_card()

  if (!is.null(subtitle)) {
    p <- p + annotate("text", x = 0.5, y = 0.42, label = subtitle, size = 4)
  }

  p
}

wrap_term <- function(x, width = 30) {
  stringr::str_wrap(as.character(x), width = width)
}

to_sentence_case <- function(x) {
  x <- as.character(x)
  x <- stringr::str_squish(x)
  out <- tolower(x)
  out <- paste0(toupper(substr(out, 1, 1)), substr(out, 2, nchar(out)))

  # Preserve standard abbreviations and symbols used in the manuscript.
  out <- stringr::str_replace_all(out, "ecm", "ECM")
  out <- stringr::str_replace_all(out, "dna", "DNA")
  out <- stringr::str_replace_all(out, "rna", "RNA")
  out <- stringr::str_replace_all(out, "cam", "CAM")
  out
}

shorten_pathway_label <- function(x) {
  x <- as.character(x)
  x <- stringr::str_replace_all(x, "_", " ")

  # Curated label harmonization for the main figure.
  # These labels are intentionally short and sentence-case. They describe
  # module-level enrichment only; they do not imply that the pathway itself is
  # increased or decreased in AD.
  x <- stringr::str_replace_all(x, regex("Developmental Cell Lineages of the Integumentary System", ignore_case = TRUE), "Developmental cell lineages")
  x <- stringr::str_replace_all(x, regex("Metabolism of xenobiotics by cytochrome P450", ignore_case = TRUE), "Xenobiotic metabolism")
  x <- stringr::str_replace_all(x, regex("Differentiation of Keratinocytes in Interfollicular Epidermis and Mammalian Skin", ignore_case = TRUE), "Keratinocyte differentiation")
  x <- stringr::str_replace_all(x, regex("Cell adhesion molecule \\(CAM\\) interaction", ignore_case = TRUE), "Cell adhesion molecule interaction")
  x <- stringr::str_replace_all(x, regex("Cell adhesion molecules", ignore_case = TRUE), "Cell adhesion molecule interaction")
  x <- stringr::str_replace_all(x, regex("Extracellular matrix organization", ignore_case = TRUE), "ECM organization")
  x <- stringr::str_replace_all(x, regex("Regulation of cellular response to growth factor stimulus", ignore_case = TRUE), "Growth-factor response")
  x <- stringr::str_replace_all(x, regex("Chemical carcinogenesis - DNA adducts", ignore_case = TRUE), "Chemical carcinogenesis")

  x <- stringr::str_squish(x)
  x <- to_sentence_case(x)
  x <- stringr::str_trunc(x, width = 42, side = "right", ellipsis = "…")
  x
}

module_network_title <- function(module_name) {
  dplyr::case_when(
    module_name == "brown"  ~ "Metabolic and epithelial signaling hubs",
    module_name == "yellow" ~ "Neuronal guidance and extracellular matrix hubs",
    TRUE ~ "Hub network"
  )
}

module_pathway_title <- function(module_name) {
  dplyr::case_when(
    module_name == "brown"  ~ "Metabolic and epithelial pathway enrichment",
    module_name == "yellow" ~ "Axonal guidance and matrix pathway enrichment",
    TRUE ~ "Significant pathway enrichment"
  )
}

get_hub_label <- function(df) {
  if ("Protein_Display" %in% names(df)) {
    out <- df$Protein_Display
  } else if ("Protein_Name" %in% names(df)) {
    out <- df$Protein_Name
  } else if ("EntrezGeneSymbol" %in% names(df)) {
    out <- df$EntrezGeneSymbol
  } else {
    out <- rep(NA_character_, nrow(df))
  }

  out <- as.character(out)

  if ("EntrezGeneSymbol" %in% names(df)) {
    eg <- as.character(df$EntrezGeneSymbol)
    out[is.na(out) | out == ""] <- eg[is.na(out) | out == ""]
  }

  out
}

find_hub_file <- function(module_name) {
  candidate <- file.path(HUB_DIR, paste0("top_hubs_", module_name, ".csv"))
  if (file.exists(candidate)) return(candidate)

  all_files <- list.files(path = HUB_DIR, pattern = "\\.csv$", full.names = TRUE)
  matched <- all_files[
    grepl(paste0("^top_hubs_", module_name, "\\.csv$"), basename(all_files), ignore.case = TRUE)
  ]

  if (length(matched) == 0) return(NULL)
  matched[1]
}

find_enrichment_files <- function(module_name) {
  # Compatible with Script 03 v3/v4 naming: *_all_terms.csv
  files_go <- list.files(
    path = ENRICH_GO_DIR,
    pattern = paste0("^enrichment_GO_BP_", module_name, "(_all_terms)?\\.csv$"),
    full.names = TRUE,
    ignore.case = TRUE
  )

  files_kegg <- list.files(
    path = ENRICH_KEGG_DIR,
    pattern = paste0("^enrichment_KEGG_", module_name, "(_all_terms)?\\.csv$"),
    full.names = TRUE,
    ignore.case = TRUE
  )

  files_react <- list.files(
    path = ENRICH_REACT_DIR,
    pattern = paste0("^enrichment_Reactome_", module_name, "(_all_terms)?\\.csv$"),
    full.names = TRUE,
    ignore.case = TRUE
  )

  list(
    GO_BP = files_go,
    KEGG = files_kegg,
    Reactome = files_react
  )
}

standardize_enrichment_df <- function(df, library_name, module_name) {
  if (is.null(df) || nrow(df) == 0) return(NULL)

  desc_candidates <- c("Description", "Term", "term", "Pathway", "pathway", "ID", "name", "Name")
  found_desc <- intersect(desc_candidates, names(df))
  if (length(found_desc) == 0) return(NULL)
  if (found_desc[1] != "Description") {
    df <- df %>% rename(Description = all_of(found_desc[1]))
  }

  padj_candidates <- c("p.adjust", "adj.P.Val", "padj", "FDR", "qvalue", "p_adj", "Adjusted.P.value", "adjusted_p_value")
  found_padj <- intersect(padj_candidates, names(df))

  if (length(found_padj) == 0) {
    pval_candidates <- c("pvalue", "p.value", "P.Value", "P_value")
    found_pval <- intersect(pval_candidates, names(df))
    if (length(found_pval) == 0) return(NULL)
    df <- df %>% rename(p.adjust = all_of(found_pval[1]))
  } else {
    if (found_padj[1] != "p.adjust") {
      df <- df %>% rename(p.adjust = all_of(found_padj[1]))
    }
  }

  if (!"Count" %in% names(df)) {
    count_candidates <- c("Gene.Count", "gene_count", "Count")
    found_count <- intersect(count_candidates, names(df))
    if (length(found_count) > 0 && found_count[1] != "Count") {
      df <- df %>% rename(Count = all_of(found_count[1]))
    } else if ("geneID" %in% names(df)) {
      df$Count <- sapply(strsplit(as.character(df$geneID), "/"), length)
    } else {
      df$Count <- 1
    }
  }

  df %>%
    mutate(
      Description = as.character(Description),
      p.adjust = suppressWarnings(as.numeric(p.adjust)),
      Count = suppressWarnings(as.numeric(Count)),
      Library = library_name,
      Module = module_name
    ) %>%
    filter(
      !is.na(Description), Description != "",
      !is.na(p.adjust), is.finite(p.adjust),
      p.adjust > 0,
      p.adjust < 0.05
    ) %>%
    mutate(
      Description = gsub("_", " ", Description),
      neglog10 = -log10(p.adjust)
    )
}

get_top_hubs <- function(module_name, n = 5) {
  file <- find_hub_file(module_name)

  if (is.null(file) || !file.exists(file)) {
    warning("No existe archivo de hubs para módulo: ", module_name)
    return(NULL)
  }

  df <- safe_read_csv(file)

  if (!"abs_kME" %in% names(df)) {
    if ("kME" %in% names(df)) {
      df <- df %>% dplyr::mutate(abs_kME = abs(kME))
    } else if ("MM" %in% names(df)) {
      df <- df %>% dplyr::mutate(abs_kME = abs(MM))
    } else {
      warning("No se encontró abs_kME/kME/MM en hubs para módulo: ", module_name)
      return(NULL)
    }
  }

  if (!"hub_rank" %in% names(df)) {
    df <- df %>%
      dplyr::arrange(dplyr::desc(abs_kME)) %>%
      dplyr::mutate(hub_rank = dplyr::row_number())
  }

  if (!"EntrezGeneSymbol" %in% names(df)) {
    df$EntrezGeneSymbol <- NA_character_
  }

  df %>%
    dplyr::mutate(
      label = get_hub_label(.),
      label = as.character(label),
      EntrezGeneSymbol = clean_text_na(EntrezGeneSymbol),
      abs_kME = suppressWarnings(as.numeric(abs_kME)),
      hub_rank = suppressWarnings(as.numeric(hub_rank))
    ) %>%
    dplyr::filter(!is.na(label), label != "") %>%
    dplyr::arrange(dplyr::desc(abs_kME), hub_rank) %>%
    dplyr::slice(seq_len(min(n, nrow(.)))) %>%
    dplyr::mutate(Module = module_name)
}

get_top_pathways_curated <- function(module_name,
                                     n_total = TOP_PATHWAYS_N,
                                     max_per_library = MAX_TERMS_PER_LIBRARY) {
  files_list <- find_enrichment_files(module_name)
  all_tbls <- list()

  for (lib in names(files_list)) {
    lib_files <- files_list[[lib]]
    if (length(lib_files) == 0) next

    df_list <- lapply(lib_files, function(f) {
      tryCatch(readr::read_csv(f, show_col_types = FALSE), error = function(e) NULL)
    })

    df_list <- df_list[!sapply(df_list, is.null)]
    if (length(df_list) == 0) next

    df_lib <- bind_rows(df_list)
    df_lib <- standardize_enrichment_df(df_lib, library_name = lib, module_name = module_name)

    if (is.null(df_lib) || nrow(df_lib) == 0) next

    df_lib <- df_lib %>%
      arrange(p.adjust) %>%
      distinct(Description, .keep_all = TRUE) %>%
      slice(seq_len(min(max_per_library, nrow(.))))

    all_tbls[[lib]] <- df_lib
  }

  if (length(all_tbls) == 0) return(NULL)

  bind_rows(all_tbls) %>%
    arrange(p.adjust) %>%
    distinct(Description, .keep_all = TRUE) %>%
    slice(seq_len(min(n_total, nrow(.))))
}

##############################################################################
# 6) LOAD INPUTS
##############################################################################

module_counts     <- safe_read_csv(MODULE_COUNT_FILE)
module_trait_long <- safe_read_csv(MODULE_TRAIT_LONG_FILE)
prioritization    <- safe_read_csv(PRIORITIZATION_FILE)
gene_module_tbl   <- safe_read_csv(GENE_MODULE_FILE)
dep_full_tbl      <- safe_read_csv(DEP_RESULTS_FILE)
module_dep        <- safe_read_csv(MODULE_DEP_SUMMARY_FILE)

load(WORKSPACE_FILE)

if (!exists("TOM")) stop("No existe TOM en el workspace.", call. = FALSE)
if (!exists("datExpr_clean")) stop("No existe datExpr_clean en el workspace.", call. = FALSE)

##############################################################################
# 7) HARMONIZE TABLES
##############################################################################

module_counts <- module_counts %>%
  mutate(Module = standardize_module_name(Module))

module_trait_long <- module_trait_long %>%
  mutate(Module = standardize_module_name(Module))

prioritization <- prioritization %>%
  mutate(Module = standardize_module_name(Module))

gene_module_tbl <- gene_module_tbl %>%
  mutate(
    Module = standardize_module_name(Module),
    EntrezGeneSymbol = clean_text_na(EntrezGeneSymbol)
  )

module_dep <- module_dep %>%
  mutate(Module = standardize_module_name(Module))

if (!"rho" %in% names(module_trait_long)) {
  rho_candidates <- c("correlation", "Correlation", "r", "estimate", "Estimate")
  found_rho <- intersect(rho_candidates, names(module_trait_long))
  if (length(found_rho) > 0) {
    module_trait_long <- module_trait_long %>% rename(rho = all_of(found_rho[1]))
  } else {
    stop("No se encontró columna rho en module_trait_results_long.csv", call. = FALSE)
  }
}

if (!"FDR" %in% names(module_trait_long)) {
  fdr_candidates <- c("qvalue", "padj", "adj_p", "adj.P.Val", "p.adjust")
  found_fdr <- intersect(fdr_candidates, names(module_trait_long))
  if (length(found_fdr) > 0) {
    module_trait_long <- module_trait_long %>% rename(FDR = all_of(found_fdr[1]))
  } else {
    stop("No se encontró columna FDR en module_trait_results_long.csv", call. = FALSE)
  }
}

if (!"N_genes" %in% names(module_counts)) {
  n_candidates <- c("n_genes", "Count", "count", "N", "size")
  found_n <- intersect(n_candidates, names(module_counts))
  if (length(found_n) > 0) {
    module_counts <- module_counts %>% rename(N_genes = all_of(found_n[1]))
  } else {
    stop("No se encontró columna N_genes en module_counts.csv", call. = FALSE)
  }
}

# DEP burden compatibility with Script 04 v6
if (!"Prop_FDR005" %in% names(module_dep) && "prop_dep_fdr_0_05" %in% names(module_dep)) {
  module_dep <- module_dep %>% rename(Prop_FDR005 = prop_dep_fdr_0_05)
}

if (!"Prop_FDR001" %in% names(module_dep) && "prop_dep_fdr_0_01" %in% names(module_dep)) {
  module_dep <- module_dep %>% rename(Prop_FDR001 = prop_dep_fdr_0_01)
}

if (!"Prop_FDR005" %in% names(module_dep)) module_dep$Prop_FDR005 <- NA_real_
if (!"Prop_FDR001" %in% names(module_dep)) module_dep$Prop_FDR001 <- NA_real_

# DEP result compatibility
if (!"adj.P.Val" %in% names(dep_full_tbl) && "FDR" %in% names(dep_full_tbl)) {
  dep_full_tbl <- dep_full_tbl %>% rename(adj.P.Val = FDR)
}

if (!"Protein_Name" %in% names(dep_full_tbl)) {
  dep_full_tbl$Protein_Name <- dep_full_tbl$EntrezGeneSymbol
}

dep_full_tbl <- dep_full_tbl %>%
  mutate(
    EntrezGeneSymbol = clean_text_na(EntrezGeneSymbol),
    Protein_Name = clean_text_na(Protein_Name),
    adj.P.Val = suppressWarnings(as.numeric(adj.P.Val)),
    logFC = suppressWarnings(as.numeric(logFC))
  ) %>%
  filter(!is.na(EntrezGeneSymbol), EntrezGeneSymbol != "") %>%
  arrange(adj.P.Val, desc(abs(logFC))) %>%
  distinct(EntrezGeneSymbol, .keep_all = TRUE) %>%
  mutate(
    dep_status = case_when(
      !is.na(adj.P.Val) & adj.P.Val < DEP_FDR_CUTOFF & !is.na(logFC) & logFC > 0 ~ "Up",
      !is.na(adj.P.Val) & adj.P.Val < DEP_FDR_CUTOFF & !is.na(logFC) & logFC < 0 ~ "Down",
      TRUE ~ "NS"
    ),
    dep_status = factor(dep_status, levels = c("Up", "Down", "NS"))
  )

MODULE_DISPLAY_MAP <- make_module_display_labels(
  modules = TOP_MODULES_HEATMAP,
  show_internal_name = DISPLAY_MODULE_INTERNAL_NAME
)

MODULE_DISPLAY_NETWORK <- make_module_display_labels(
  modules = TOP_MODULES_NETWORK,
  show_internal_name = TRUE
)

MODULE_DISPLAY_NETWORK_MAIN <- make_module_display_labels(
  modules = TOP_MODULES_NETWORK_MAIN,
  show_internal_name = TRUE
)

##############################################################################
# 8) PANEL A — DENDROGRAM
##############################################################################

convert_pdf_first_page_to_png(DENDRO_PDF, DENDRO_PNG, dpi = 300)
panel_a <- panel_from_png(DENDRO_PNG)

##############################################################################
# 9) PANEL B — MODULE SIZE BARPLOT
##############################################################################

panel_b_df <- module_counts %>%
  dplyr::filter(Module != "grey") %>%
  dplyr::mutate(
    N_genes = as.numeric(N_genes),
    is_priority = Module %in% TOP_MODULES_HEATMAP,
    fill_group = ifelse(is_priority, Module, "other"),
    Module = factor(Module, levels = Module[order(-N_genes)])
  )

fill_vals_b <- c(MODULE_COLORS[TOP_MODULES_HEATMAP], other = "grey85")

panel_b <- ggplot(panel_b_df, aes(x = Module, y = N_genes, fill = fill_group)) +
  geom_col(width = 0.82, color = COL_TEXT, linewidth = 0.30) +
  geom_text(aes(label = scales::comma(N_genes)), vjust = -0.35, size = 3.2, color = COL_TEXT) +
  scale_fill_manual(values = fill_vals_b, guide = "none") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.10))) +
  labs(
    title = "Module size distribution",
    subtitle = "Prioritized modules highlighted; remaining modules shown in grey",
    x = NULL,
    y = "Genes per module"
  ) +
  theme_pub() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
  )

##############################################################################
# 10) PANEL C — MODULE–TRAIT HEATMAP
##############################################################################

heatmap_df <- module_trait_long %>%
  dplyr::filter(Module %in% TOP_MODULES_HEATMAP, Trait %in% TRAITS_MAIN) %>%
  dplyr::mutate(
    Module = as.character(Module),
    Trait = as.character(Trait),
    rho = as.numeric(rho),
    FDR = as.numeric(FDR),
    Module_display = unname(MODULE_DISPLAY_MAP[Module]),
    Trait_display = TRAIT_LABELS[Trait],
    stars = add_sig_stars(FDR)
  ) %>%
  dplyr::filter(!is.na(Module_display), !is.na(Trait_display))

heatmap_df$Module_display <- factor(
  heatmap_df$Module_display,
  levels = unname(MODULE_DISPLAY_MAP[TOP_MODULES_HEATMAP])
)

heatmap_df$Trait_display <- factor(
  heatmap_df$Trait_display,
  levels = TRAIT_LABELS[TRAITS_MAIN]
)

rho_lim <- max(abs(heatmap_df$rho), na.rm = TRUE)
if (!is.finite(rho_lim)) rho_lim <- 0.5
rho_lim <- max(rho_lim, 0.35)

side_df <- tibble(
  Module = TOP_MODULES_HEATMAP,
  Module_display = factor(
    unname(MODULE_DISPLAY_MAP[TOP_MODULES_HEATMAP]),
    levels = unname(MODULE_DISPLAY_MAP[TOP_MODULES_HEATMAP])
  ),
  x = 1
)

panel_c_side <- ggplot(side_df, aes(x = x, y = Module_display, fill = Module)) +
  geom_tile(width = 1, height = 0.98, color = NA) +
  scale_fill_manual(values = MODULE_COLORS[TOP_MODULES_HEATMAP], guide = "none") +
  scale_x_continuous(expand = c(0, 0)) +
  theme_void() +
  theme(
    plot.margin = margin(28, 0, 48, 4),
    plot.background = element_rect(fill = "white", color = NA)
  )

panel_c_heat <- ggplot(heatmap_df, aes(x = Trait_display, y = Module_display, fill = rho)) +
  geom_tile(color = "grey90", linewidth = 0.5) +
  geom_text(aes(label = stars), size = 4.2, color = "black") +
  scale_fill_gradient2(
    low = "#6FA8DC",
    mid = "white",
    high = "#E06666",
    midpoint = 0,
    limits = c(-rho_lim, rho_lim),
    name = "Spearman\nrho",
    breaks = c(-0.5, 0, 0.5)
  ) +
  labs(
    title = "Module–trait relationships",
    subtitle = "BH-FDR corrected significance overlaid as stars",
    x = NULL,
    y = NULL
  ) +
  theme_pub() +
  theme(
    panel.border = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    axis.text.y = element_text(face = "bold", color = COL_TEXT),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, color = COL_TEXT),
    legend.position = "right",
    plot.margin = margin(10, 10, 10, 0)
  )

panel_c <- cowplot::plot_grid(
  panel_c_side,
  panel_c_heat,
  nrow = 1,
  rel_widths = c(0.04, 0.96),
  align = "h",
  axis = "tb"
)

##############################################################################
# 11) PREPARE DATA FOR REAL NETWORK PORTRAITS
##############################################################################

hub_tbl <- purrr::map_dfr(TOP_MODULES_NETWORK, function(m) {
  x <- get_top_hubs(m, n = TOP_HUBS_N)

  if (is.null(x) || nrow(x) == 0) {
    tibble(
      Module = m,
      EntrezGeneSymbol = NA_character_,
      label = NA_character_,
      abs_kME = NA_real_,
      hub_rank = NA_real_
    )
  } else {
    x
  }
})

path_tbl <- purrr::map_dfr(TOP_MODULES_NETWORK, function(m) {
  x <- get_top_pathways_curated(m)

  if (is.null(x) || nrow(x) == 0) {
    tibble(
      Module = m,
      Description = NA_character_,
      Count = NA_real_,
      neglog10 = NA_real_,
      p.adjust = NA_real_,
      Library = NA_character_
    )
  } else {
    x
  }
})

module_dep_detail_tbl <- gene_module_tbl %>%
  mutate(
    Module = as.character(Module),
    EntrezGeneSymbol = clean_text_na(EntrezGeneSymbol)
  ) %>%
  filter(Module %in% TOP_MODULES_NETWORK) %>%
  filter(!is.na(EntrezGeneSymbol), EntrezGeneSymbol != "") %>%

  # IMPORTANT:
  # gene_module_tbl may already contain DEP columns from previous scripts.
  # If we do not remove them before the join, dplyr creates duplicated columns
  # such as adj.P.Val.x / adj.P.Val.y, and build_dep_composition() fails because
  # adj.P.Val no longer exists as a clean column.
  select(-any_of(c("logFC", "adj.P.Val", "dep_status"))) %>%

  left_join(
    dep_full_tbl %>%
      select(
        EntrezGeneSymbol,
        logFC,
        adj.P.Val,
        dep_status
      ),
    by = "EntrezGeneSymbol"
  ) %>%
  mutate(
    dep_status = forcats::fct_na_value_to_level(dep_status, level = "NS"),
    dep_status = factor(as.character(dep_status), levels = c("Up", "Down", "NS"))
  )

dep_comp_tbl <- module_dep_detail_tbl %>%
  count(Module, dep_status, name = "n") %>%
  group_by(Module) %>%
  mutate(
    total_n = sum(n),
    prop = n / total_n
  ) %>%
  ungroup()

safe_write_csv(hub_tbl, file.path(OUTDIR_TABLES, "hub_table_used.csv"))
safe_write_csv(path_tbl, file.path(OUTDIR_TABLES, "pathway_table_used.csv"))
safe_write_csv(module_dep_detail_tbl, file.path(OUTDIR_TABLES, "module_dep_detail_used.csv"))
safe_write_csv(dep_comp_tbl, file.path(OUTDIR_TABLES, "module_dep_composition_used.csv"))

##############################################################################
# 12) BUILD REAL NETWORK PANELS
##############################################################################

build_header_strip <- function(module_name, module_label) {
  ggplot() +
    geom_rect(
      aes(xmin = 0, xmax = 1, ymin = 0, ymax = 1),
      fill = "white", color = COL_BORDER, linewidth = 0.6
    ) +
    geom_rect(
      aes(xmin = 0, xmax = 0.18, ymin = 0, ymax = 1),
      fill = MODULE_COLORS[module_name], color = NA
    ) +
    annotate(
      "text", x = 0.24, y = 0.50,
      label = module_label,
      hjust = 0, vjust = 0.5,
      size = 7.2, fontface = "bold", color = COL_TEXT
    ) +
    coord_cartesian(xlim = c(0, 1), ylim = c(0, 1), clip = "off") +
    theme_void() +
    theme(plot.margin = margin(0, 0, 4, 0))
}

build_real_network <- function(module_name) {

  genes_all <- colnames(datExpr_clean)

  hub_seed <- get_top_hubs(module_name, n = N_SEED_HUBS)

  if (is.null(hub_seed) || nrow(hub_seed) == 0) {
    return(blank_placeholder("No hubs available", "TOM-based network could not be constructed"))
  }

  hub_seed <- hub_seed %>%
    filter(!is.na(EntrezGeneSymbol), EntrezGeneSymbol != "") %>%
    distinct(EntrezGeneSymbol, .keep_all = TRUE)

  if (nrow(hub_seed) == 0) {
    return(blank_placeholder("No valid hub symbols", "Hub table has no usable EntrezGeneSymbol"))
  }

  module_genes <- gene_module_tbl %>%
    filter(Module == module_name) %>%
    mutate(EntrezGeneSymbol = clean_text_na(EntrezGeneSymbol)) %>%
    filter(!is.na(EntrezGeneSymbol), EntrezGeneSymbol != "") %>%
    distinct(EntrezGeneSymbol, .keep_all = TRUE)

  module_idx <- match(module_genes$EntrezGeneSymbol, genes_all)
  valid_mod <- which(!is.na(module_idx))

  if (length(valid_mod) < 2) {
    return(blank_placeholder("Insufficient module overlap", "Module genes not found in datExpr_clean"))
  }

  module_genes_valid <- module_genes$EntrezGeneSymbol[valid_mod]
  module_idx_valid   <- module_idx[valid_mod]

  hub_idx <- match(hub_seed$EntrezGeneSymbol, genes_all)
  valid_hub <- which(!is.na(hub_idx))

  if (length(valid_hub) < 2) {
    return(blank_placeholder("Insufficient TOM overlap", "Seed hubs not found in datExpr_clean"))
  }

  hub_seed <- hub_seed[valid_hub, , drop = FALSE]
  hub_idx  <- hub_idx[valid_hub]

  neighbor_symbols <- c()

  for (i in seq_along(hub_idx)) {
    tom_vec <- TOM[hub_idx[i], module_idx_valid]
    names(tom_vec) <- module_genes_valid

    tom_vec <- tom_vec[names(tom_vec) != hub_seed$EntrezGeneSymbol[i]]
    tom_vec <- sort(tom_vec, decreasing = TRUE)

    if (length(tom_vec) > 0) {
      neighbor_symbols <- c(
        neighbor_symbols,
        names(tom_vec)[seq_len(min(N_NEIGHBORS_PER_HUB, length(tom_vec)))]
      )
    }
  }

  neighbor_symbols <- unique(neighbor_symbols)

  hub_nodes <- hub_seed %>%
    transmute(
      EntrezGeneSymbol,
      label = ifelse(is.na(label) | label == "", EntrezGeneSymbol, label),
      abs_kME = abs_kME,
      hub_rank = hub_rank,
      node_type = "hub"
    )

  neighbor_nodes <- tibble(
    EntrezGeneSymbol = neighbor_symbols
  ) %>%
    filter(!EntrezGeneSymbol %in% hub_nodes$EntrezGeneSymbol) %>%
    left_join(
      gene_module_tbl %>%
        filter(Module == module_name) %>%
        transmute(
          EntrezGeneSymbol = clean_text_na(EntrezGeneSymbol),
          label = get_hub_label(.)
        ) %>%
        distinct(EntrezGeneSymbol, .keep_all = TRUE),
      by = "EntrezGeneSymbol"
    ) %>%
    mutate(
      label = ifelse(is.na(label) | label == "", EntrezGeneSymbol, label),
      abs_kME = NA_real_,
      hub_rank = NA_real_,
      node_type = "neighbor"
    )

  node_tbl <- bind_rows(hub_nodes, neighbor_nodes) %>%
    distinct(EntrezGeneSymbol, .keep_all = TRUE) %>%
    mutate(
      abs_kME = ifelse(is.na(abs_kME), 0.45, abs_kME),
      node_fill = ifelse(node_type == "hub", MODULE_COLORS[module_name], "grey92")
    )

  idx <- match(node_tbl$EntrezGeneSymbol, genes_all)
  valid <- which(!is.na(idx))

  if (length(valid) < 2) {
    return(blank_placeholder("Insufficient final node overlap", "Expanded network not found in datExpr_clean"))
  }

  node_tbl <- node_tbl[valid, , drop = FALSE]
  idx <- idx[valid]

  tom_sub <- TOM[idx, idx, drop = FALSE]
  diag(tom_sub) <- 0

  edge_df <- expand.grid(
    from_idx = seq_len(nrow(tom_sub)),
    to_idx   = seq_len(ncol(tom_sub)),
    KEEP.OUT.ATTRS = FALSE,
    stringsAsFactors = FALSE
  ) %>%
    mutate(
      weight = as.numeric(tom_sub[cbind(from_idx, to_idx)])
    ) %>%
    filter(from_idx < to_idx) %>%
    filter(!is.na(weight), is.finite(weight))

  edge_df_thr <- edge_df %>%
    filter(weight >= EDGE_TOM_THRESHOLD) %>%
    arrange(desc(weight))

  if (nrow(edge_df_thr) < MIN_EDGES_IF_SPARSE) {
    edge_df_thr <- edge_df %>%
      arrange(desc(weight)) %>%
      slice(seq_len(min(MIN_EDGES_IF_SPARSE, nrow(.))))
  }

  if (nrow(edge_df_thr) < 10) {
    edge_df_thr <- edge_df %>%
      arrange(desc(weight)) %>%
      slice(seq_len(min(60, nrow(.))))
  }

  edge_df_thr <- edge_df_thr %>%
    slice(seq_len(min(MAX_EDGES_TO_PLOT, nrow(.)))) %>%
    mutate(
      from = node_tbl$EntrezGeneSymbol[from_idx],
      to   = node_tbl$EntrezGeneSymbol[to_idx]
    ) %>%
    filter(!is.na(from), !is.na(to), from != to) %>%
    distinct(from, to, .keep_all = TRUE)

  if (nrow(edge_df_thr) == 0) {
    return(blank_placeholder("No TOM edges recovered", "Module remains too sparse even after fallback"))
  }

  nodes_graph <- node_tbl %>%
    transmute(
      name = EntrezGeneSymbol,
      label,
      abs_kME,
      hub_rank,
      node_type,
      node_fill
    )

  edges_graph <- edge_df_thr %>%
    transmute(from, to, weight)

  used_nodes <- unique(c(edges_graph$from, edges_graph$to))
  nodes_graph <- nodes_graph %>% filter(name %in% used_nodes)

  graph_tbl <- tidygraph::tbl_graph(
    nodes = nodes_graph,
    edges = edges_graph,
    directed = FALSE
  )

  ggraph(graph_tbl, layout = "stress") +
    ggraph::geom_edge_link(
      aes(width = weight),
      colour = "grey84",
      alpha = 0.28,
      show.legend = FALSE
    ) +
    ggraph::geom_node_point(
      aes(size = abs_kME, fill = node_fill, shape = node_type),
      colour = MODULE_COLORS[module_name],
      stroke = 0.55,
      show.legend = FALSE
    ) +
    ggraph::geom_node_text(
      aes(label = ifelse(node_type == "hub" & !is.na(hub_rank) & hub_rank <= LABEL_TOP_NODES, label, "")),
      repel = TRUE,
      size = 2.75,
      fontface = "bold",
      colour = COL_TEXT,
      family = BASE_FONT_FAMILY,
      max.overlaps = Inf
    ) +
    scale_fill_identity() +
    scale_shape_manual(
      values = c(
        hub = 21,
        neighbor = 21
      )
    ) +
    scale_size_continuous(range = c(3.0, 7.2)) +
    scale_edge_width(range = c(0.08, 0.55)) +
    labs(
      title = module_network_title(module_name),
      subtitle = "Eight labelled hubs with strongest TOM-based neighbors"
    ) +
    theme_void_card()
}

# DEP-direction composition panel removed in v6.1.
# Rationale: WGCNA modules reflect co-expression structure, whereas DEP direction
# comes from a separate AD vs CN model and may be visually misleading in module portraits.

build_pathway_bubbles <- function(module_name) {
  df_path <- path_tbl %>%
    filter(Module == module_name) %>%
    filter(!is.na(Description), Description != "", !is.na(neglog10))

  if (nrow(df_path) == 0) {
    return(blank_placeholder("No enrichment available"))
  }

  df_path <- df_path %>%
    arrange(neglog10) %>%
    mutate(
      Description = shorten_pathway_label(Description),
      Description = wrap_term(Description, 22),
      Description = factor(Description, levels = Description),
      Library = factor(Library, levels = c("GO_BP", "Reactome", "KEGG"))
    )

  ggplot(df_path, aes(x = neglog10, y = Description)) +
    geom_segment(
      aes(x = 0, xend = neglog10, yend = Description),
      color = "grey88", linewidth = 0.6
    ) +
    geom_point(
      aes(size = Count),
      fill = MODULE_COLORS[module_name],
      shape = 21,
      color = "white",
      stroke = 0.85
    ) +
    scale_size_continuous(range = c(3.5, 8.5)) +
    labs(
      title = module_pathway_title(module_name),
      subtitle = expression(paste("Significant module enrichment; bubble size = gene count; x = ", -log[10], "(adjusted p)")),
      x = expression(-log[10]("adjusted p")),
      y = NULL
    ) +
    theme_card() +
    theme(
      axis.text.y = element_text(size = 9.6, color = COL_TEXT),
      panel.grid.major.x = element_line(color = COL_GRID, linewidth = 0.5)
    )
}

build_module_portrait <- function(module_name) {
  module_label <- unname(MODULE_DISPLAY_NETWORK[module_name])

  p_header <- build_header_strip(module_name, module_label)
  p_net    <- build_real_network(module_name)
  p_path   <- build_pathway_bubbles(module_name)

  bottom_row <- patchwork::wrap_plots(
    p_net, p_path,
    ncol = 2,
    widths = c(1.15, 1.00)
  )

  patchwork::wrap_plots(
    p_header,
    bottom_row,
    ncol = 1,
    heights = c(0.12, 0.88)
  )
}

##############################################################################
# 12B) PANEL D — INTEGRATED PRIORITIZATION SCATTER
##############################################################################

if (!"biological_score" %in% names(prioritization)) {
  if ("enrichment_score" %in% names(prioritization)) {
    prioritization$biological_score <- prioritization$enrichment_score
  } else if ("total_enrichment_terms" %in% names(prioritization)) {
    prioritization$biological_score <- safe_numeric(prioritization$total_enrichment_terms)
  } else {
    prioritization$biological_score <- 0
  }
}

if (!"clinical_score" %in% names(prioritization)) {
  if ("mean_abs_trait_rho" %in% names(prioritization)) {
    prioritization$clinical_score <- safe_numeric(prioritization$mean_abs_trait_rho) * 40
  } else {
    prioritization$clinical_score <- 0
  }
}

if (!"hub_score" %in% names(prioritization)) {
  if ("mean_abs_kME" %in% names(prioritization)) {
    prioritization$hub_score <- safe_numeric(prioritization$mean_abs_kME) * 30
  } else {
    prioritization$hub_score <- 10
  }
}

prioritization_plot <- prioritization %>%
  dplyr::filter(Module != "grey") %>%
  dplyr::mutate(
    biological_score = safe_numeric(biological_score),
    clinical_score = safe_numeric(clinical_score),
    hub_score = safe_numeric(hub_score),
    is_main = Module %in% TOP_MODULES_HEATMAP,
    label = dplyr::case_when(
      Module == "black" ~ "M1/black",
      Module == "brown" ~ "M2/brown",
      Module == "yellow" ~ "M3/yellow",
      TRUE ~ NA_character_
    )
  )

panel_d_prioritization <- ggplot(prioritization_plot) +
  geom_point(
    data = prioritization_plot %>% dplyr::filter(!is_main),
    aes(x = biological_score, y = clinical_score),
    color = "grey80",
    fill = "grey92",
    size = 2.5,
    shape = 21,
    stroke = 0.3,
    alpha = 0.75
  ) +
  geom_point(
    data = prioritization_plot %>% dplyr::filter(is_main),
    aes(x = biological_score, y = clinical_score, size = hub_score, fill = Module),
    color = COL_TEXT,
    shape = 21,
    stroke = 0.5,
    alpha = 0.98
  ) +
  ggrepel::geom_text_repel(
    data = prioritization_plot %>% dplyr::filter(is_main),
    aes(x = biological_score, y = clinical_score, label = label),
    size = 4.0,
    color = COL_TEXT,
    max.overlaps = Inf,
    box.padding = 0.35,
    point.padding = 0.25
  ) +
  scale_fill_manual(values = MODULE_COLORS, guide = "none") +
  scale_size_continuous(name = "Hub score", range = c(4.5, 9.5)) +
  labs(
    title = "Integrated module prioritization",
    x = "Biological richness score",
    y = "Clinical association score"
  ) +
  theme_pub() +
  theme(
    legend.position = c(0.83, 0.23),
    legend.background = element_rect(fill = "white", color = NA),
    plot.title = element_text(hjust = 0.5, face = "plain")
  )

##############################################################################
# 12C) PANEL E/F — BIOLOGICAL PORTRAITS
##############################################################################

portraits_list <- lapply(TOP_MODULES_NETWORK, build_module_portrait)
names(portraits_list) <- TOP_MODULES_NETWORK

portraits_list_main <- portraits_list[TOP_MODULES_NETWORK_MAIN]

panel_portraits_main <- patchwork::wrap_plots(
  plots = portraits_list_main,
  ncol = 1
) +
  patchwork::plot_annotation(
    title = "Hub-centered module networks and significant enrichment",
    subtitle = NULL,
    theme = theme(
      plot.title = element_text(size = TITLE_SIZE, face = "bold", hjust = 0.5, color = COL_TEXT),
      plot.margin = margin(5, 5, 5, 5)
    )
  )

# No extended black portrait is generated in this version.
# Black remains represented in panel C and panel D only, because it lacks significant enrichment.

##############################################################################
# 13) SUPPLEMENTARY PRIORITIZATION SCATTER
##############################################################################

# Compatibility with current Script 04 prioritization table.
if (!"biological_score" %in% names(prioritization)) {
  if ("enrichment_score" %in% names(prioritization)) {
    prioritization$biological_score <- prioritization$enrichment_score
  } else {
    prioritization$biological_score <- 0
  }
}

if (!"clinical_score" %in% names(prioritization)) {
  if ("mean_abs_trait_rho" %in% names(prioritization)) {
    prioritization$clinical_score <- scales::rescale(
      safe_numeric(prioritization$mean_abs_trait_rho),
      to = c(0, 1),
      from = range(safe_numeric(prioritization$mean_abs_trait_rho), na.rm = TRUE)
    )
  } else {
    prioritization$clinical_score <- 0
  }
}

if (!"hub_score" %in% names(prioritization)) {
  if ("mean_abs_kME" %in% names(prioritization)) {
    prioritization$hub_score <- scales::rescale(
      safe_numeric(prioritization$mean_abs_kME),
      to = c(0, 1),
      from = range(safe_numeric(prioritization$mean_abs_kME), na.rm = TRUE)
    )
  } else {
    prioritization$hub_score <- 0
  }
}

panel_s1_bg <- prioritization %>%
  dplyr::filter(Module != "grey")

panel_s1_fg <- prioritization %>%
  dplyr::filter(Module %in% TOP_MODULES_HEATMAP) %>%
  dplyr::mutate(label = unname(MODULE_DISPLAY_MAP[Module]))

panel_s1 <- ggplot() +
  geom_point(
    data = panel_s1_bg,
    aes(x = biological_score, y = clinical_score),
    color = "grey80",
    fill = "grey93",
    size = 4,
    shape = 21,
    stroke = 0.3
  ) +
  geom_point(
    data = panel_s1_fg,
    aes(
      x = biological_score,
      y = clinical_score,
      size = hub_score,
      fill = Module
    ),
    color = COL_TEXT,
    shape = 21,
    stroke = 0.4,
    alpha = 0.95
  ) +
  geom_text(
    data = panel_s1_fg,
    aes(x = biological_score, y = clinical_score, label = label),
    nudge_y = 0.07,
    size = 4
  ) +
  scale_fill_manual(values = MODULE_COLORS, guide = "none") +
  scale_size_continuous(name = "Hub score", range = c(4, 9)) +
  labs(
    title = "Integrated module prioritization",
    x = "Biological richness score",
    y = "Clinical association score"
  ) +
  theme_pub() +
  theme(legend.position = "top")

##############################################################################
# 14) FINAL LAYOUT
##############################################################################

# Balanced main composite:
# panels a-d are placed in a true 2 x 2 grid with equal widths/heights so the
# dendrogram, barplot, heatmap and prioritization panel have the same visual
# hierarchy. The portraits occupy the lower block.
top_grid <- (
  (panel_a | panel_b) /
    (panel_c | panel_d_prioritization)
) +
  patchwork::plot_layout(
    widths = c(1, 1),
    heights = c(1, 1)
  )

figure3 <- patchwork::wrap_plots(
  top_grid,
  panel_portraits_main,
  ncol = 1,
  heights = c(1.55, 1.65)
) +
  patchwork::plot_annotation(
    tag_levels = "a",
    theme = theme(
      plot.tag = element_text(size = 20, face = "bold", color = COL_TEXT),
      plot.margin = margin(4, 4, 4, 4)
    )
  )


##############################################################################
# 15) SAVE
##############################################################################

save_pub_both(
  plot_obj = figure3,
  filename_base = file.path(OUTDIR, "Figure3_WGCNA_main_v6_8_FINAL_bugfix"),
  dims = c(14, 13.8)
)

save_pub_both(
  plot_obj = panel_a,
  filename_base = file.path(OUTDIR_PANELS, "Figure3_panel_a_dendrogram"),
  dims = c(10, 4.5)
)

save_pub_both(
  plot_obj = panel_b,
  filename_base = file.path(OUTDIR_PANELS, "Figure3_panel_b_module_size"),
  dims = c(11, 5)
)

save_pub_both(
  plot_obj = panel_c,
  filename_base = file.path(OUTDIR_PANELS, "Figure3_panel_c_module_trait_heatmap"),
  dims = c(13, 5.6)
)

for (m in names(portraits_list)) {
  save_pub_both(
    plot_obj = portraits_list[[m]],
    filename_base = file.path(OUTDIR_PANELS, paste0("Figure3_panel_d_portrait_", m)),
    dims = c(14, 5.2)
  )
}

save_pub_both(
  plot_obj = panel_d_prioritization,
  filename_base = file.path(OUTDIR_PANELS, "Figure3_panel_d_prioritization"),
  dims = c(6.5, 5.2)
)

save_pub_both(
  plot_obj = panel_portraits_main,
  filename_base = file.path(OUTDIR_PANELS, "Figure3_panel_e_f_module_portraits_main"),
  dims = c(14, 8.0)
)

save_pub_both(
  plot_obj = panel_s1,
  filename_base = file.path(OUTDIR_SUPP, "Supplementary_module_prioritization_scatter"),
  dims = c(8, 6)
)

##############################################################################
# 16) FINAL SUMMARY
##############################################################################

figure3_summary <- tibble::tibble(
  metric = c(
    "base_dir",
    "outdir",
    "wgcna_input_level",
    "top_modules_heatmap",
    "top_modules_network",
    "pathway_color_encoding",
    "pathway_direction_note",
    "main_figure_file"
  ),
  value = c(
    BASE_DIR,
    OUTDIR,
    "GENE-COLLAPSED, not aptamer-level",
    paste(TOP_MODULES_HEATMAP, collapse = ", "),
    paste(TOP_MODULES_NETWORK, collapse = ", "),
    "module-colored bubbles (not GO/KEGG/Reactome colors)",
    "enrichment reflects module biology, not AD up/down direction",
    file.path(OUTDIR, "Figure3_WGCNA_main_v6_8_FINAL_bugfix.pdf")
  )
)

safe_write_csv(
  figure3_summary,
  file.path(OUTDIR_TABLES, "figure3_summary.csv")
)

writeLines(
  capture.output(utils::sessionInfo()),
  con = file.path(OUTDIR, "sessionInfo.txt")
)

cat("\nFigure 3 exportada correctamente en:\n", OUTDIR, "\n")
cat("\nPaneles separados exportados en:\n", OUTDIR_PANELS, "\n")
cat("\nSupplementary exportado en:\n", OUTDIR_SUPP, "\n")
cat("\nTablas auxiliares exportadas en:\n", OUTDIR_TABLES, "\n")
cat("\nMódulos seleccionados para heatmap:\n", paste(TOP_MODULES_HEATMAP, collapse = ", "), "\n")
cat("\nMódulos seleccionados para red:\n", paste(TOP_MODULES_NETWORK, collapse = ", "), "\n")

###############################################################################
# END
###############################################################################

