###############################################################################
# ReDLat plasma proteomics — machine-learning workflow
# 24. Audit ML publication outputs
# Requires: publication-candidate files generated by Scripts 16–23
# Produces: privacy/completeness audit reports
###############################################################################

from pathlib import Path
import sys
_REPO_HINT = Path(__file__).resolve()
for _candidate in [_REPO_HINT.parent, *_REPO_HINT.parents]:
    if (_candidate / ".redlat-root").exists() or (_candidate / ".here").exists():
        PROJECT_ROOT = _candidate
        break
else:
    raise FileNotFoundError("Repository root not found. Set REDLAT_PROJECT_ROOT.")
sys.path.insert(0, str(PROJECT_ROOT / "python"))
from redlat_ml.config import load_config
CONFIG = load_config(__file__)

import json
import re
import pandas as pd
from openpyxl import load_workbook

PUBLIC_ROOT = CONFIG.publication_root
AUDIT_DIR = PUBLIC_ROOT / "publication_audit"
AUDIT_DIR.mkdir(parents=True, exist_ok=True)

identifier_names = {
    "sampleid", "sample_id", "participantid", "participant_id",
    "subjectid", "subject_id", "record_id", "match_pair_id", "subclass",
    "study_id", "reviewer_id",
}
path_patterns = [
    re.compile(r"[A-Za-z]:[/\\]Users[/\\]", re.I),
    re.compile(r"/Users/[^/]+/", re.I),
    re.compile(r"/home/[^/]+/", re.I),
]
pseudonym_pattern = re.compile(r"\bRDLAT_[A-F0-9]{8,}\b", re.I)

def text_hits(value: object):
    text = "" if value is None else str(value)
    path_hits = sum(len(p.findall(text)) for p in path_patterns)
    pseudo_hits = len(pseudonym_pattern.findall(text))
    return path_hits, pseudo_hits

rows = []
for path in sorted(PUBLIC_ROOT.rglob("*")):
    if not path.is_file():
        continue
    # The audit reports from a previous run are outputs of this audit itself;
    # inspect them too, but all recorded paths inside them are relative.
    record = {
        "file": str(path.relative_to(PUBLIC_ROOT)),
        "suffix": path.suffix.lower(),
        "size_bytes": path.stat().st_size,
        "identifier_columns": "",
        "personal_path_hits": 0,
        "pseudonym_hits": 0,
        "status": "pass",
        "note": "",
    }
    try:
        suffix = path.suffix.lower()
        if suffix == ".csv":
            df = pd.read_csv(path, low_memory=False)
            found = sorted({str(c).strip().lower() for c in df.columns} & identifier_names)
            record["identifier_columns"] = ";".join(found)
            for col in df.columns:
                if pd.api.types.is_object_dtype(df[col]) or pd.api.types.is_string_dtype(df[col]):
                    for value in df[col].dropna().astype(str):
                        p, q = text_hits(value)
                        record["personal_path_hits"] += p
                        record["pseudonym_hits"] += q
        elif suffix == ".xlsx":
            wb = load_workbook(path, read_only=True, data_only=True)
            found = set()
            for ws in wb.worksheets:
                for row in ws.iter_rows(values_only=True):
                    for value in row:
                        low = str(value).strip().lower() if value is not None else ""
                        if low in identifier_names:
                            found.add(low)
                        p, q = text_hits(value)
                        record["personal_path_hits"] += p
                        record["pseudonym_hits"] += q
            record["identifier_columns"] = ";".join(sorted(found))
        elif suffix in {".txt", ".md", ".json", ".py", ".r", ".yaml", ".yml"}:
            content = path.read_text(encoding="utf-8", errors="ignore")
            p, q = text_hits(content)
            record["personal_path_hits"] += p
            record["pseudonym_hits"] += q
    except Exception as exc:
        record["note"] = f"inspection warning: {exc}"

    if record["identifier_columns"] or record["personal_path_hits"] or record["pseudonym_hits"]:
        record["status"] = "fail"
    rows.append(record)

audit = pd.DataFrame(rows)
audit.to_csv(AUDIT_DIR / "ml_publication_file_audit.csv", index=False)
failed_files = int((audit["status"] == "fail").sum()) if len(audit) else 0
summary = {
    "publication_root": "outputs/ML/publication",
    "files_checked": int(len(audit)),
    "failed_files": failed_files,
    "status": "pass" if len(audit) and failed_files == 0 else "review",
}
(AUDIT_DIR / "ml_publication_audit_summary.json").write_text(
    json.dumps(summary, indent=2), encoding="utf-8"
)
if failed_files:
    failed = audit.loc[audit["status"] == "fail", "file"].tolist()
    raise RuntimeError("Publication audit failed for: " + ", ".join(failed))
print(json.dumps(summary, indent=2))
