###############################################################################
# ReDLat plasma proteomics — machine-learning workflow
# 24. Audit ML publication outputs
# Requires: publication-candidate files generated by Scripts 16–23
# Produces: privacy, completeness and workbook audit reports
# Data policy: participant-level inputs and predictions remain local.
###############################################################################

from pathlib import Path
import sys

_REPO_HINT = Path(__file__).resolve()
for _candidate in [_REPO_HINT.parent, *_REPO_HINT.parents]:
    if (_candidate / ".redlat-root").exists() or (_candidate / ".here").exists():
        PROJECT_ROOT = _candidate
        break
else:
    raise FileNotFoundError("Repository root not found. Set REDLAT_PROJECT_ROOT.")
sys.path.insert(0, str(PROJECT_ROOT / "python"))
from redlat_ml.config import load_config, require_files
CONFIG = load_config(__file__)

from pathlib import Path
import json
import re
import zipfile
import pandas as pd
from openpyxl import load_workbook

PUBLIC_ROOT = CONFIG.publication_root
AUDIT_DIR = CONFIG.public_root / "publication_audit"
AUDIT_DIR.mkdir(parents=True, exist_ok=True)

identifier_names = {
    "sampleid", "sample_id", "participantid", "participant_id",
    "subjectid", "subject_id", "record_id", "match_pair_id", "subclass",
}
path_patterns = [
    re.compile(r"[A-Za-z]:[/\\]Users[/\\]", re.I),
    re.compile(r"/Users/[^/]+/", re.I),
    re.compile(r"/home/[^/]+/", re.I),
]

rows = []
for path in sorted(PUBLIC_ROOT.rglob("*")):
    if not path.is_file():
        continue
    record = {
        "file": str(path.relative_to(PUBLIC_ROOT)),
        "suffix": path.suffix.lower(),
        "size_bytes": path.stat().st_size,
        "identifier_columns": "",
        "personal_path_hits": 0,
        "status": "pass",
        "note": "",
    }
    try:
        if path.suffix.lower() == ".csv":
            df = pd.read_csv(path, nrows=20)
            found = sorted({str(c).strip().lower() for c in df.columns} & identifier_names)
            record["identifier_columns"] = ";".join(found)
        elif path.suffix.lower() == ".xlsx":
            wb = load_workbook(path, read_only=True, data_only=True)
            found = set()
            for ws in wb.worksheets:
                for row in ws.iter_rows(min_row=1, max_row=min(ws.max_row or 1, 8), values_only=True):
                    for value in row:
                        if str(value).strip().lower() in identifier_names:
                            found.add(str(value).strip().lower())
            record["identifier_columns"] = ";".join(sorted(found))
        if path.suffix.lower() in {".txt", ".md", ".csv", ".py", ".r"}:
            content = path.read_text(encoding="utf-8", errors="ignore")
            record["personal_path_hits"] = sum(len(pattern.findall(content)) for pattern in path_patterns)
    except Exception as exc:
        record["note"] = f"inspection warning: {exc}"
    if record["identifier_columns"] or record["personal_path_hits"]:
        record["status"] = "fail"
    rows.append(record)

audit = pd.DataFrame(rows)
audit.to_csv(AUDIT_DIR / "ml_publication_file_audit.csv", index=False)
summary = {
    "publication_root": str(PUBLIC_ROOT),
    "files_checked": int(len(audit)),
    "failed_files": int((audit["status"] == "fail").sum()) if len(audit) else 0,
    "status": "pass" if len(audit) and (audit["status"] == "fail").sum() == 0 else "review",
}
(AUDIT_DIR / "ml_publication_audit_summary.json").write_text(
    json.dumps(summary, indent=2), encoding="utf-8"
)
if summary["failed_files"]:
    failed = audit.loc[audit["status"] == "fail", "file"].tolist()
    raise RuntimeError("Publication audit failed for: " + ", ".join(failed))
print(json.dumps(summary, indent=2))
